import { format, resolveConfig } from 'prettier'
import type { HatsuProfile } from '@black-whale/nen-engine'

/**
 * Renders the compiled registry as TypeScript.
 *
 * It is committed rather than built into `.svelte-kit`: a generated file that
 * shows up in the diff is a generated file whose changes get read, and the
 * whole point of compiling this table is that a change to it is a change to
 * the canon. `--check` in CI is what keeps it honest.
 */

const HEADER = `// Generated by \`pnpm --filter @black-whale/canon-compiler compile:hatsu\`.
// Do not edit: rerun the compiler. The facts come from
// data/abilities/abilities.json (id, name), data/characters/characters.json
// (owner) and each module's \`site\` block (the rest) — edit those.

import type { HatsuProfile } from '@black-whale/nen-engine'
`

/** Single quotes, the repo's default, unless the text itself holds one. */
function literal(value: string): string {
  const escaped = value.replace(/\\/g, '\\\\')
  return escaped.includes("'") ? `"${escaped.replace(/"/g, '\\"')}"` : `'${escaped}'`
}

function renderProfile(profile: HatsuProfile): string {
  const fields: Array<[string, string]> = [
    ['id', profile.id],
    ['name', profile.name],
    ['owner', profile.owner],
    ['kind', profile.kind],
    ['instruction', profile.instruction],
    ['rule', profile.rule],
    ['cost', profile.cost],
    ['color', profile.color],
    ['action', profile.action],
  ]
  const body = fields.map(([key, value]) => `    ${key}: ${literal(value)},`).join('\n')
  return `  {\n${body}\n  },`
}

/**
 * Prettier has the last word on the layout rather than this file guessing at
 * its rules: the output has to survive `pnpm format:check` unchanged, and the
 * only way to be sure of that is to hand it to the formatter the check runs.
 */
export async function emitHatsuProfiles(
  profiles: readonly HatsuProfile[],
  filepath: string,
): Promise<string> {
  const entries = profiles.map(renderProfile).join('\n')
  const ids = profiles.map((profile) => `  | ${literal(profile.id)}`).join('\n')
  const source = `${HEADER}
/**
 * Every ability the site casts, as a type.
 *
 * A locale catalogue keyed by \`HatsuId\` is exhaustive or it does not compile:
 * a hatsu added without its French text, or a translation left behind by a
 * removal, is a type error rather than a page that quietly falls back to
 * English. \`compile:hatsu --skeleton\` writes the missing entries out.
 */
export type HatsuId =
${ids}

export const HATSU_PROFILES: HatsuProfile[] = [
${entries}
]
`
  const config = await resolveConfig(filepath)
  return format(source, { ...config, filepath })
}
