import { format, resolveConfig } from 'prettier'
import type { AbilityInteractionManifest } from '@black-whale/nen-engine'
import { literal } from './emit.js'

/**
 * Renders the compiled interaction manifests as TypeScript.
 *
 * Committed like the registry, and for the same reason: the day a technique
 * stops accepting a target it used to accept, that is a change to what a
 * visitor can do, and it belongs in the diff.
 */

const HEADER = `// Generated by \`pnpm --filter @black-whale/canon-compiler compile:hatsu\`.
// Do not edit: rerun the compiler. The facts come from each module's
// \`interactionManifest\` — edit those.

import type { AbilityInteractionManifest } from '@black-whale/nen-engine'
`

function list(values: readonly string[]): string {
  return `[${values.map(literal).join(', ')}]`
}

function renderManifest(manifest: AbilityInteractionManifest): string {
  const lines = [
    `    abilityId: ${literal(manifest.abilityId)},`,
    `    entryPoints: {`,
    `      actions: ${list(manifest.entryPoints.actions)},`,
    `      requiredState: ${list(manifest.entryPoints.requiredState)},`,
    `    },`,
    `    inputMode: ${literal(manifest.inputMode)},`,
    `    allowedTargets: ${list(manifest.allowedTargets)},`,
    `    overlays: ${list(manifest.overlays)},`,
  ]
  const transition = manifest.perspectiveTransition
  if (transition) {
    lines.push(
      `    perspectiveTransition: {`,
      `      canChangeBody: ${String(transition.canChangeBody)},`,
      `      canChangeConsciousness: ${String(transition.canChangeConsciousness)},`,
      `      canFollowAura: ${String(transition.canFollowAura)},`,
      `    },`,
    )
  }
  if (manifest.customComponent) {
    lines.push(`    customComponent: ${literal(manifest.customComponent)},`)
  }
  return `  {\n${lines.join('\n')}\n  },`
}

export async function emitInteractionManifests(
  manifests: readonly AbilityInteractionManifest[],
  filepath: string,
): Promise<string> {
  const entries = manifests.map(renderManifest).join('\n')
  const source = `${HEADER}
/**
 * How each ability the site casts is interacted with: the gesture it is driven
 * by, what it may be pointed at, the overlays it asks for, and the state its
 * entry requires.
 *
 * Both renderers read this table. What the DOM layer and the 3D tour still own
 * is *how* a cast looks once it is allowed — not whether it may be aimed at a
 * body, a solid or a room, which is declared here once.
 */
export const INTERACTION_MANIFESTS: AbilityInteractionManifest[] = [
${entries}
]
`
  const config = await resolveConfig(filepath)
  return format(source, { ...config, filepath })
}
