export type Verdict = 'infected' | 'refused' | 'cancelled' | 'forced'

export type Rider =
  | 'bound'
  | 'moon'
  | 'stolen'
  | 'sworn'
  | 'smoke'
  | 'taxed'
  | 'trapped'
  | 'deterred'
  | 'solicited'

export type Aftermath =
  | 'bound'
  | 'moon'
  | 'stolen'
  | 'sworn-struck'
  | 'smoke'
  | 'taxed'
  | 'trapped'
  | 'deterred'
  | 'solicited'
  | 'proxied'
  | 'evicted'
  | 'avenged'
  | 'unaffordable'
  | 'burnt-out'
  | 'stood-in'
