FROM node:20-alpine AS builder
RUN apk add --no-cache openssl libc6-compat
RUN corepack enable
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @black-whale/database generate
RUN pnpm turbo build --filter=@black-whale/api

FROM node:20-alpine AS runner
RUN apk add --no-cache openssl libc6-compat
RUN corepack enable
WORKDIR /app
COPY --from=builder /app /app
ENV NODE_ENV=production
EXPOSE 3001
USER node
CMD ["node", "apps/api/dist/main.js"]
