import type { StrategyScenarioV2 } from './types'

export const LOCKDOWN_SCENARIO: StrategyScenarioV2 = {
  schemaVersion: 2,
  id: 'succession-lockdown-400',
  contentVersion: 1,
  title: 'State of Emergency',
  description: 'The lockdown tightens the succession war around the royal quarters.',
  chapterNumber: 400,
  maxTurns: 8,
  defaultDifficulty: 'EXPERT',
  playableFactions: [
    {
      factionId: 'prince-woble',
      doctrine: 'INTELLIGENCE',
      initialLocationId: 'tier-1-royal-residential-sector-room-1014',
      requiredCharacterIds: ['kurapika', 'queen-oito', 'bill'],
      publicObjective: {
        id: 'woble-survive',
        kind: 'FORM_BASTION',
        title: 'Preserve the Sanctuary',
        description: 'Keep three defenders together.',
        target: 3,
        secret: false,
      },
      secretObjective: {
        id: 'woble-watch',
        kind: 'CONFIRM_HOSTILES',
        title: 'Read the Encircling',
        description: 'Confirm three adversaries.',
        target: 3,
        secret: true,
      },
    },
    {
      factionId: 'prince-benjamin',
      doctrine: 'EXPANSION',
      initialLocationId: 'tier-1-royal-residential-sector-room-1001',
      requiredCharacterIds: ['prince-benjamin', 'balsamilco-might', 'musse'],
      publicObjective: {
        id: 'benjamin-control',
        kind: 'OCCUPY_DISTINCT',
        title: 'Enforce the Emergency',
        description: 'Occupy four sectors.',
        target: 4,
        secret: false,
      },
      secretObjective: {
        id: 'benjamin-watch',
        kind: 'CONFIRM_HOSTILES',
        title: 'Identify Suspects',
        description: 'Confirm three adversaries.',
        target: 3,
        secret: true,
      },
    },
    {
      factionId: 'prince-camilla',
      doctrine: 'CONSOLIDATION',
      initialLocationId: 'tier-1-royal-residential-sector-room-1002',
      requiredCharacterIds: ['prince-camilla', 'sarahell', 'moswana'],
      publicObjective: {
        id: 'camilla-hold',
        kind: 'FORM_BASTION',
        title: 'Reject Isolation',
        description: 'Gather three units.',
        target: 3,
        secret: false,
      },
      secretObjective: {
        id: 'camilla-reach',
        kind: 'OCCUPY_DISTINCT',
        title: 'Extend Relays',
        description: 'Occupy three sectors.',
        target: 3,
        secret: true,
      },
    },
  ],
  locationIds: [
    'tier-1',
    'tier-1-banquet-hall',
    'tier-1-royal-residential-sector',
    'tier-1-royal-residential-sector-room-1001',
    'tier-1-royal-residential-sector-room-1002',
    'tier-1-royal-residential-sector-room-1004',
    'tier-1-royal-residential-sector-room-1005',
    'tier-1-royal-residential-sector-room-1009',
    'tier-1-royal-residential-sector-room-1012',
    'tier-1-royal-residential-sector-room-1013',
    'tier-1-royal-residential-sector-room-1014',
  ],
  events: [
    {
      id: 'lockdown-alert',
      turn: 1,
      kind: 'ALERT',
      title: 'Mobilization',
      description: 'Guards take position.',
      aiMoveMultiplier: 1.25,
    },
    {
      id: 'lockdown-blackout',
      turn: 3,
      kind: 'BLACKOUT',
      title: 'Channels Cut',
      description: 'Royal communications are jammed.',
      aiMoveMultiplier: 1,
    },
    {
      id: 'lockdown-seal',
      turn: 6,
      kind: 'LOCKDOWN',
      title: 'Sectors Sealed',
      description: 'Movements become risky.',
      aiMoveMultiplier: 0.5,
    },
  ],
  failureConditions: ['TURN_LIMIT', 'FACTION_ELIMINATED'],
  provenance: [
    {
      sourceId: 'chapter-400',
      chapter: 400,
      note: 'Non-canonical projection of a tightening of Deck 1 security.',
    },
  ],
}
