import type { StrategyScenarioV2 } from './types'

export const MAFIA_WAR_SCENARIO: StrategyScenarioV2 = {
  schemaVersion: 2,
  id: 'mafia-war-390',
  contentVersion: 1,
  title: 'Lower Deck War',
  description:
    'Xi-Yu, Cha-R, and Heil-Ly dispute the passages and intelligence between decks 2 to 5.',
  chapterNumber: 390,
  maxTurns: 8,
  defaultDifficulty: 'NORMAL',
  playableFactions: [
    {
      factionId: 'mafia-xiyu',
      doctrine: 'INTELLIGENCE',
      initialLocationId: 'tier-4-xi-yu-family-office',
      requiredCharacterIds: ['hinrigh-biganduffno', 'lynch-fullbokko', 'zakuro-custard'],
      publicObjective: {
        id: 'xiyu-intel',
        kind: 'CONFIRM_HOSTILES',
        title: 'Map the Threat',
        description: 'Confirm three hostile agents.',
        target: 3,
        secret: false,
      },
      secretObjective: {
        id: 'xiyu-hold',
        kind: 'FORM_BASTION',
        title: 'Protect the Family',
        description: 'Keep two agents at the Xi-Yu office.',
        target: 2,
        secret: true,
      },
    },
    {
      factionId: 'mafia-char',
      doctrine: 'CONSOLIDATION',
      initialLocationId: 'tier-5-cha-r-family-office',
      requiredCharacterIds: ['keni-wang', 'brocco-li', 'padaille'],
      publicObjective: {
        id: 'char-bastion',
        kind: 'FORM_BASTION',
        title: 'Hold Deck 5',
        description: 'Form a bastion of two agents.',
        target: 2,
        secret: false,
      },
      secretObjective: {
        id: 'char-routes',
        kind: 'OCCUPY_DISTINCT',
        title: 'Keep the Routes',
        description: 'Occupy three sectors.',
        target: 3,
        secret: true,
      },
    },
    {
      factionId: 'mafia-heilly',
      doctrine: 'EXPANSION',
      initialLocationId: 'tier-2-heilly-secret-hideout',
      requiredCharacterIds: ['morena-prudo', 'dogman', 'yokotani'],
      publicObjective: {
        id: 'heilly-spread',
        kind: 'OCCUPY_DISTINCT',
        title: 'Spread Chaos',
        description: 'Occupy four distinct sectors.',
        target: 4,
        secret: false,
      },
      secretObjective: {
        id: 'heilly-scout',
        kind: 'CONFIRM_HOSTILES',
        title: 'Choose Next Targets',
        description: 'Confirm two hostile agents.',
        target: 2,
        secret: true,
      },
    },
  ],
  locationIds: [
    'tier-2',
    'tier-2-heilly-secret-hideout',
    'tier-2-bulkhead',
    'tier-3',
    'tier-3-heilly-family-office',
    'tier-4',
    'tier-4-xi-yu-family-office',
    'tier-4-central-passage',
    'tier-5',
    'tier-5-cha-r-family-office',
    'tier-5-central-dining-hall',
    'tier-5-warehouse',
  ],
  events: [
    {
      id: 'mafia-alert',
      turn: 2,
      kind: 'ALERT',
      title: 'Search Notice',
      description: 'The families accelerate their searches.',
      aiMoveMultiplier: 1.25,
    },
    {
      id: 'mafia-blackout',
      turn: 5,
      kind: 'BLACKOUT',
      title: 'Network Jammed',
      description: 'Clandestine communications are interrupted.',
      aiMoveMultiplier: 1,
    },
    {
      id: 'mafia-lockdown',
      turn: 7,
      kind: 'LOCKDOWN',
      title: 'Watertight Doors',
      description: 'Passages between decks are slowed.',
      aiMoveMultiplier: 0.5,
    },
  ],
  failureConditions: ['TURN_LIMIT', 'FACTION_ELIMINATED'],
  provenance: [
    {
      sourceId: 'chapter-390',
      chapter: 390,
      note: 'Conflict between the three mafias on the lower decks.',
    },
  ],
}
