<script lang="ts">
  /**
   * The Black Whale in longitudinal section, generated from
   * `data/ship/blueprint.json` by `scripts/generate-section-map.py`.
   *
   * Cut on the centreline, looking to starboard, bow to the left — the view of
   * the ch. 349 double page, drawn from the reconstruction instead of traced.
   * One unit is 0.4253 m; the section has its own scale because 175 m of ship
   * and 77 m of freeboard do not fit the deck plans' 0.35 m per unit.
   *
   * Rooms the cut passes through are solid, labelled where the label fits, and
   * open their deck. Rooms it passes beside — everything to port or starboard —
   * are drawn behind and dim: they are what fills the ship, and on the manga
   * page they are the strips of texture between the labelled callouts.
   *
   * The banded gaps are the decks this reconstruction does not hold. The ship
   * has 41 of them and the tour walks 5, so about thirteen metres of ship sit
   * between each pair. Nothing is drawn inside them, because nothing is known
   * to be.
   *
   * The band over tier 1 is the same admission, and it is open at the top: the
   * ch. 369 exterior shows a liner terraced a dozen levels above the one floor
   * of it anyone has drawn a plan for. Closing that band at a height would be a
   * claim about how tall the liner is, and the page gives its shape, not its
   * scale.
   *
   * Do not hand-edit — regenerate from the blueprint.
   */
  import { mapState } from '$lib/state/mapState.svelte'
  import { locale, t } from '$lib/i18n'

  type Room = {
    id: string
    tier: string
    region: string | null
    x: number
    y: number
    w: number
    h: number
    label: string
    name: string
    size: number
    at: [number, number]
    cut: boolean
    through: boolean
    inferred: boolean
  }

  const rooms: Room[] = [
    {
      id: 'tier-4-recycling-sewage-facilities',
      tier: 'tier-4',
      region: 't4-recycling',
      x: 111.87,
      y: 415.13,
      w: 600.69,
      h: 18.81,
      label: '',
      name: 'Recycling & Sewage Facilities',
      size: 0,
      at: [412.2, 424.5],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-technical-recycling',
      tier: 'tier-5',
      region: 't4-recycling',
      x: 136.56,
      y: 489.19,
      w: 493.72,
      h: 18.81,
      label: '',
      name: 'Technical & Recycling Level',
      size: 0,
      at: [383.4, 498.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-forward-corridor',
      tier: 'tier-3',
      region: null,
      x: 136.56,
      y: 345.78,
      w: 559.54,
      h: 14.11,
      label: '',
      name: 'Forward Corridor',
      size: 0,
      at: [416.3, 352.8],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-aft-corridor',
      tier: 'tier-3',
      region: null,
      x: 136.56,
      y: 345.78,
      w: 559.54,
      h: 14.11,
      label: '',
      name: 'Aft Corridor',
      size: 0,
      at: [416.3, 352.8],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-king-living-quarters',
      tier: 'tier-1',
      region: 'king-quarters',
      x: 177.7,
      y: 190.61,
      w: 452.58,
      h: 16.46,
      label: '',
      name: "King's Living Quarters",
      size: 0,
      at: [404.0, 198.8],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-2-bulkhead',
      tier: 'tier-2',
      region: 't2-security',
      x: 136.56,
      y: 270.55,
      w: 576.0,
      h: 11.75,
      label: '',
      name: 'Tier 2 Bulkhead',
      size: 0,
      at: [424.6, 276.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-banquet-hall',
      tier: 'tier-1',
      region: 'banquet-hall',
      x: 218.85,
      y: 185.91,
      w: 313.86,
      h: 21.16,
      label: '',
      name: 'Banquet Hall',
      size: 0,
      at: [375.8, 196.5],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-forward-corridor',
      tier: 'tier-4',
      region: null,
      x: 120.1,
      y: 423.36,
      w: 592.46,
      h: 10.58,
      label: '',
      name: 'Forward Corridor',
      size: 0,
      at: [416.3, 428.6],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-aft-corridor',
      tier: 'tier-4',
      region: null,
      x: 144.79,
      y: 423.36,
      w: 567.77,
      h: 10.58,
      label: '',
      name: 'Aft Corridor',
      size: 0,
      at: [428.7, 428.6],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-forward-corridor',
      tier: 'tier-2',
      region: null,
      x: 218.85,
      y: 270.55,
      w: 452.57,
      h: 11.75,
      label: '',
      name: 'Forward Corridor',
      size: 0,
      at: [445.1, 276.4],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-main-corridor',
      tier: 'tier-2',
      region: null,
      x: 218.85,
      y: 270.55,
      w: 452.57,
      h: 11.75,
      label: '',
      name: 'Main Corridor',
      size: 0,
      at: [445.1, 276.4],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-aft-corridor',
      tier: 'tier-2',
      region: null,
      x: 218.85,
      y: 270.55,
      w: 452.57,
      h: 11.75,
      label: '',
      name: 'Aft Corridor',
      size: 0,
      at: [445.1, 276.4],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-aft-corridor',
      tier: 'tier-5',
      region: null,
      x: 144.79,
      y: 497.42,
      w: 493.71,
      h: 10.58,
      label: '',
      name: 'Aft Corridor',
      size: 0,
      at: [391.6, 502.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-screening-room',
      tier: 'tier-2',
      region: 't2-screening-room',
      x: 218.85,
      y: 258.79,
      w: 205.71,
      h: 23.51,
      label: '',
      name: 'Screening Room',
      size: 0,
      at: [321.7, 270.5],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-forward-corridor',
      tier: 'tier-5',
      region: null,
      x: 161.25,
      y: 497.42,
      w: 444.34,
      h: 10.58,
      label: '',
      name: 'Forward Corridor',
      size: 0,
      at: [383.4, 502.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-royal-approach',
      tier: 'tier-1',
      region: null,
      x: 218.85,
      y: 195.31,
      w: 370.28,
      h: 11.76,
      label: '',
      name: 'Banquet Hall Vestibule',
      size: 0,
      at: [404.0, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-aft-promenade',
      tier: 'tier-1',
      region: null,
      x: 218.85,
      y: 195.31,
      w: 370.28,
      h: 11.76,
      label: '',
      name: 'Aft Promenade',
      size: 0,
      at: [404.0, 201.2],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-central-passage',
      tier: 'tier-4',
      region: 'tier-4-central-passage',
      x: 144.79,
      y: 423.36,
      w: 407.31,
      h: 10.58,
      label: '',
      name: 'Central Passage Tier 4–5',
      size: 0,
      at: [348.4, 428.6],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-4-secondary-passage',
      tier: 'tier-4',
      region: null,
      x: 144.79,
      y: 423.36,
      w: 407.31,
      h: 10.58,
      label: '',
      name: 'Secondary Transport Route',
      size: 0,
      at: [348.4, 428.6],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-5-transverse-corridor',
      tier: 'tier-5',
      region: null,
      x: 342.28,
      y: 497.42,
      w: 263.31,
      h: 10.58,
      label: '',
      name: 'Transverse Corridor',
      size: 0,
      at: [473.9, 502.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-central-hospital',
      tier: 'tier-3',
      region: 't3-hospital',
      x: 342.28,
      y: 345.78,
      w: 164.57,
      h: 14.11,
      label: '',
      name: 'Central Hospital',
      size: 0,
      at: [424.6, 352.8],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-cineplex',
      tier: 'tier-3',
      region: 't3-cinema',
      x: 539.76,
      y: 341.08,
      w: 123.43,
      h: 18.81,
      label: '',
      name: 'Cineplex',
      size: 0,
      at: [601.5, 350.5],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-c-aft-passage',
      tier: 'tier-1-c',
      region: null,
      x: 288.79,
      y: 169.22,
      w: 325.03,
      h: 7.05,
      label: '',
      name: 'Aft Passage',
      size: 0,
      at: [451.3, 172.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-vip-quarters',
      tier: 'tier-2',
      region: null,
      x: 218.85,
      y: 270.55,
      w: 181.03,
      h: 11.75,
      label: '',
      name: 'VIP Quarters',
      size: 0,
      at: [309.4, 276.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-residential-first-class',
      tier: 'tier-3',
      region: 't3-residential-1st',
      x: 161.25,
      y: 345.78,
      w: 148.11,
      h: 14.11,
      label: '',
      name: 'First-Class Residential Block',
      size: 0,
      at: [235.3, 352.8],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-supreme-court',
      tier: 'tier-1-b',
      region: 'supreme-court',
      x: 613.82,
      y: 165.69,
      w: 98.74,
      h: 18.81,
      label: '',
      name: 'Supreme Court',
      size: 0,
      at: [663.2, 175.1],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-heilly-family-office',
      tier: 'tier-3',
      region: 't3-heilly',
      x: 539.76,
      y: 345.78,
      w: 123.43,
      h: 14.11,
      label: '',
      name: 'Heil-Ly Family Office',
      size: 0,
      at: [601.5, 352.8],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-2-ministry-of-justice',
      tier: 'tier-2',
      region: 't2-justice',
      x: 441.02,
      y: 270.55,
      w: 148.11,
      h: 11.75,
      label: '',
      name: 'Ministry of Justice',
      size: 0,
      at: [515.1, 276.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-standard-cabins-aft',
      tier: 'tier-5',
      region: 't5-residential',
      x: 161.25,
      y: 497.42,
      w: 148.11,
      h: 10.58,
      label: '',
      name: 'Tier 5 Standard Cabins (aft)',
      size: 0,
      at: [235.3, 502.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-central-dining-hall',
      tier: 'tier-5',
      region: 'central-dining-hall',
      x: 457.48,
      y: 486.84,
      w: 74.05,
      h: 21.16,
      label: '',
      name: 'Central Dining Hall',
      size: 0,
      at: [494.5, 497.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-central-courthouse',
      tier: 'tier-3',
      region: 'central-courthouse',
      x: 424.56,
      y: 341.08,
      w: 82.29,
      h: 18.81,
      label: '',
      name: 'Central Courthouse',
      size: 0,
      at: [465.7, 350.5],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-center-north',
      tier: 'tier-4',
      region: null,
      x: 276.45,
      y: 423.36,
      w: 131.65,
      h: 10.58,
      label: '',
      name: 'Central General Area (forward)',
      size: 0,
      at: [342.3, 428.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-center-south',
      tier: 'tier-4',
      region: null,
      x: 276.45,
      y: 423.36,
      w: 131.65,
      h: 10.58,
      label: '',
      name: 'Central General Area (aft)',
      size: 0,
      at: [342.3, 428.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-corridor-aft',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 391.65,
      y: 195.31,
      w: 115.2,
      h: 11.76,
      label: '',
      name: "Guards' Round (aft)",
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-4-royal-army-conference-room',
      tier: 'tier-4',
      region: 'royal-army-office',
      x: 424.56,
      y: 423.36,
      w: 123.43,
      h: 10.58,
      label: '',
      name: 'Kakin Royal Army Conference Room',
      size: 0,
      at: [486.3, 428.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-medical-clinic',
      tier: 'tier-4',
      region: null,
      x: 424.56,
      y: 423.36,
      w: 123.43,
      h: 10.58,
      label: '',
      name: 'Tier 4 Medical Clinic',
      size: 0,
      at: [486.3, 428.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-banquet-hall-service-end',
      tier: 'tier-1',
      region: 'banquet-hall',
      x: 532.71,
      y: 185.91,
      w: 56.42,
      h: 22.57,
      label: '',
      name: 'Banquet Hall (service end)',
      size: 0,
      at: [560.9, 197.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-west-north',
      tier: 'tier-4',
      region: null,
      x: 144.79,
      y: 423.36,
      w: 115.2,
      h: 10.58,
      label: '',
      name: 'West General Area (forward)',
      size: 0,
      at: [202.4, 428.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-west-south',
      tier: 'tier-4',
      region: null,
      x: 144.79,
      y: 423.36,
      w: 115.2,
      h: 10.58,
      label: '',
      name: 'West General Area (aft)',
      size: 0,
      at: [202.4, 428.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-1',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 101.09,
      h: 11.76,
      label: '',
      name: 'Cross Gap 1',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-2',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 101.09,
      h: 11.76,
      label: '',
      name: 'Cross Gap 2',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-3',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 101.09,
      h: 11.76,
      label: '',
      name: 'Cross Gap 3',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-4',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 101.09,
      h: 11.76,
      label: '',
      name: 'Cross Gap 4',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-5',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 101.09,
      h: 11.76,
      label: '',
      name: 'Cross Gap 5',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-6',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 101.09,
      h: 11.76,
      label: '',
      name: 'Cross Gap 6',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-7',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 101.09,
      h: 11.76,
      label: '',
      name: 'Cross Gap 7',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-8',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 101.09,
      h: 11.76,
      label: '',
      name: 'Cross Gap 8',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-court-void',
      tier: 'tier-1',
      region: null,
      x: 613.82,
      y: 195.31,
      w: 98.74,
      h: 11.76,
      label: '',
      name: 'Starboard Aft Floor',
      size: 0,
      at: [663.2, 201.2],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-3-central-police-station',
      tier: 'tier-3',
      region: 'central-police-station',
      x: 342.28,
      y: 345.78,
      w: 82.28,
      h: 14.11,
      label: '',
      name: 'Central Police Station',
      size: 0,
      at: [383.4, 352.8],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-residential-units',
      tier: 'tier-3',
      region: 'central-police-station',
      x: 342.28,
      y: 345.78,
      w: 82.28,
      h: 14.11,
      label: '',
      name: 'Central Police Dorm Room',
      size: 0,
      at: [383.4, 352.8],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-3-bulkhead-access',
      tier: 'tier-3',
      region: null,
      x: 383.42,
      y: 345.78,
      w: 82.28,
      h: 14.11,
      label: '',
      name: 'Emergency Bulkhead to Tier 2',
      size: 0,
      at: [424.6, 352.8],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-5-cha-r-family-office',
      tier: 'tier-5',
      region: 't5-char',
      x: 342.28,
      y: 497.42,
      w: 98.74,
      h: 10.58,
      label: '',
      name: 'Cha-R Family Office',
      size: 0,
      at: [391.6, 502.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-garrison-void',
      tier: 'tier-1',
      region: null,
      x: 510.96,
      y: 195.31,
      w: 78.17,
      h: 11.76,
      label: '',
      name: 'Starboard Quarters Floor',
      size: 0,
      at: [550.0, 201.2],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-2-vip-witness-protection-area',
      tier: 'tier-2',
      region: 't2-justice',
      x: 593.25,
      y: 270.55,
      w: 78.17,
      h: 11.75,
      label: '',
      name: 'VIP Witness Protection Area',
      size: 0,
      at: [632.3, 276.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vip-casino',
      tier: 'tier-1-c',
      region: 'casino',
      x: 288.79,
      y: 157.46,
      w: 41.14,
      h: 18.81,
      label: '',
      name: 'VIP Casino',
      size: 0,
      at: [309.4, 166.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-2-heilly-secret-hideout',
      tier: 'tier-2',
      region: 't2-vip',
      x: 403.99,
      y: 270.55,
      w: 61.71,
      h: 11.75,
      label: '',
      name: 'Heil-Ly Secret Hideout',
      size: 0,
      at: [434.8, 276.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-residential-room-3101',
      tier: 'tier-3',
      region: 'room-3101',
      x: 161.25,
      y: 345.78,
      w: 49.37,
      h: 14.11,
      label: '',
      name: 'Room 3101 (Heil-Ly Trap)',
      size: 0,
      at: [185.9, 352.8],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-area-37564',
      tier: 'tier-5',
      region: 'room-37564',
      x: 202.39,
      y: 497.42,
      w: 65.83,
      h: 10.58,
      label: '',
      name: 'Area 37564',
      size: 0,
      at: [235.3, 502.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-hangar-entrance',
      tier: 'tier-5',
      region: 'tier-5-hangar-entrance',
      x: 605.59,
      y: 497.42,
      w: 65.83,
      h: 10.58,
      label: '',
      name: 'Hangar Entrance',
      size: 0,
      at: [638.5, 502.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-void',
      tier: 'tier-1',
      region: null,
      x: 334.05,
      y: 195.31,
      w: 53.48,
      h: 11.76,
      label: '',
      name: 'Port Central Floor',
      size: 0,
      at: [360.8, 201.2],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-5-medical-clinic',
      tier: 'tier-5',
      region: 't5-medical-none',
      x: 547.99,
      y: 497.42,
      w: 57.6,
      h: 10.58,
      label: '',
      name: 'Tier 5 Medical Clinic',
      size: 0,
      at: [576.8, 502.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-soldiers-living-quarters',
      tier: 'tier-1-b',
      region: 'soldiers-living-quarters',
      x: 510.96,
      y: 177.45,
      w: 78.17,
      h: 7.05,
      label: '',
      name: "Soldiers' Living Quarters",
      size: 0,
      at: [550.0, 181.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-princes-burial-chamber',
      tier: 'tier-1',
      region: 'princes-burial-chamber',
      x: 385.28,
      y: 192.96,
      w: 37.42,
      h: 14.11,
      label: '',
      name: "Princes' Burial Chamber",
      size: 0,
      at: [404.0, 200.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-prison-beyond',
      tier: 'tier-1-b',
      region: 'beyond-cell',
      x: 626.16,
      y: 177.45,
      w: 74.06,
      h: 7.05,
      label: '',
      name: "Beyond Netero's Holding Cell",
      size: 0,
      at: [663.2, 181.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vip-jail',
      tier: 'tier-1-b',
      region: 'vip-detention',
      x: 626.16,
      y: 177.45,
      w: 74.06,
      h: 7.05,
      label: '',
      name: 'VIP Jail',
      size: 0,
      at: [663.2, 181.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-casino-void',
      tier: 'tier-1',
      region: null,
      x: 288.79,
      y: 195.31,
      w: 41.14,
      h: 11.76,
      label: '',
      name: 'Port Inner Floor',
      size: 0,
      at: [309.4, 201.2],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1001',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1001',
      x: 452.77,
      y: 195.31,
      w: 39.97,
      h: 11.76,
      label: '',
      name: 'Room 1001 (Benjamin)',
      size: 0,
      at: [472.8, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1002',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1002',
      x: 405.75,
      y: 195.31,
      w: 39.97,
      h: 11.76,
      label: '',
      name: 'Room 1002 (Camilla)',
      size: 0,
      at: [425.7, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1003',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1003',
      x: 452.77,
      y: 195.31,
      w: 39.97,
      h: 11.76,
      label: '',
      name: 'Room 1003 (Zhang Lei)',
      size: 0,
      at: [472.8, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1004',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1004',
      x: 405.75,
      y: 195.31,
      w: 39.97,
      h: 11.76,
      label: '',
      name: 'Room 1004 (Tserriednich)',
      size: 0,
      at: [425.7, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1005',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1005',
      x: 452.77,
      y: 195.31,
      w: 39.97,
      h: 11.76,
      label: '',
      name: 'Room 1005 (Tubeppa)',
      size: 0,
      at: [472.8, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1006',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1006',
      x: 405.75,
      y: 195.31,
      w: 39.97,
      h: 11.76,
      label: '',
      name: 'Room 1006 (Tyson)',
      size: 0,
      at: [425.7, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1007',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1007',
      x: 452.77,
      y: 195.31,
      w: 39.97,
      h: 11.76,
      label: '',
      name: 'Room 1007 (Luzurus)',
      size: 0,
      at: [472.8, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1008',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1008',
      x: 405.75,
      y: 195.31,
      w: 39.97,
      h: 11.76,
      label: '',
      name: 'Room 1008 (Salé-salé)',
      size: 0,
      at: [425.7, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1009',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1009',
      x: 452.77,
      y: 195.31,
      w: 39.97,
      h: 11.76,
      label: '',
      name: 'Room 1009 (Halkenburg)',
      size: 0,
      at: [472.8, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1010',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1010',
      x: 405.75,
      y: 195.31,
      w: 39.97,
      h: 11.76,
      label: '',
      name: 'Room 1010 (Kacho)',
      size: 0,
      at: [425.7, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1011',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1011',
      x: 452.77,
      y: 195.31,
      w: 39.97,
      h: 11.76,
      label: '',
      name: 'Room 1011 (Fugetsu)',
      size: 0,
      at: [472.8, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1012',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1012',
      x: 405.75,
      y: 195.31,
      w: 39.97,
      h: 11.76,
      label: '',
      name: 'Room 1012 (Momoze)',
      size: 0,
      at: [425.7, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1013',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1013',
      x: 452.77,
      y: 195.31,
      w: 39.97,
      h: 11.76,
      label: '',
      name: 'Room 1013 (Marayam)',
      size: 0,
      at: [472.8, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1014',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1014',
      x: 405.75,
      y: 195.31,
      w: 39.97,
      h: 11.76,
      label: '',
      name: 'Room 1014 (Woble)',
      size: 0,
      at: [425.7, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-cabin-cross-corridor-west',
      tier: 'tier-5',
      region: null,
      x: 161.25,
      y: 497.42,
      w: 41.14,
      h: 10.58,
      label: '',
      name: 'Cabin Cross Corridor (west)',
      size: 0,
      at: [181.8, 502.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-cabin-cross-corridor-east',
      tier: 'tier-5',
      region: null,
      x: 268.22,
      y: 497.42,
      w: 41.14,
      h: 10.58,
      label: '',
      name: 'Cabin Cross Corridor (east)',
      size: 0,
      at: [288.8, 502.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-tier-1-access',
      tier: 'tier-2',
      region: null,
      x: 427.03,
      y: 270.55,
      w: 36.21,
      h: 11.75,
      label: '',
      name: 'Tier 1 Stairwell',
      size: 0,
      at: [445.1, 276.4],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-vvip-restricted-royal-01',
      tier: 'tier-1',
      region: null,
      x: 218.85,
      y: 195.31,
      w: 31.73,
      h: 11.76,
      label: '',
      name: 'Restricted Royal Suite 1',
      size: 0,
      at: [234.7, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-restricted-royal-02',
      tier: 'tier-1',
      region: null,
      x: 218.85,
      y: 195.31,
      w: 31.73,
      h: 11.76,
      label: '',
      name: 'Restricted Royal Suite 2',
      size: 0,
      at: [234.7, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-suite-01',
      tier: 'tier-1',
      region: null,
      x: 218.85,
      y: 195.31,
      w: 31.73,
      h: 11.76,
      label: '',
      name: 'VVIP Suite 1',
      size: 0,
      at: [234.7, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-suite-02',
      tier: 'tier-1',
      region: null,
      x: 218.85,
      y: 195.31,
      w: 31.73,
      h: 11.76,
      label: '',
      name: 'VVIP Suite 2',
      size: 0,
      at: [234.7, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-suite-03',
      tier: 'tier-1',
      region: null,
      x: 257.64,
      y: 195.31,
      w: 27.03,
      h: 11.76,
      label: '',
      name: 'VVIP Suite 3',
      size: 0,
      at: [271.2, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-suite-04',
      tier: 'tier-1',
      region: null,
      x: 257.64,
      y: 195.31,
      w: 27.03,
      h: 11.76,
      label: '',
      name: 'VVIP Suite 4',
      size: 0,
      at: [271.2, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-mafia-suite',
      tier: 'tier-1',
      region: null,
      x: 257.64,
      y: 195.31,
      w: 27.03,
      h: 11.76,
      label: '',
      name: 'Mafia VVIP Suite',
      size: 0,
      at: [271.2, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-v5-suite',
      tier: 'tier-1',
      region: null,
      x: 257.64,
      y: 195.31,
      w: 27.03,
      h: 11.76,
      label: '',
      name: "V5 Politician's Suite",
      size: 0,
      at: [271.2, 201.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-service-corridor-forward',
      tier: 'tier-5',
      region: null,
      x: 441.02,
      y: 497.42,
      w: 16.46,
      h: 10.58,
      label: '',
      name: 'Passage to the Great Refectory',
      size: 0,
      at: [449.2, 502.7],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-5-service-corridor-aft',
      tier: 'tier-5',
      region: null,
      x: 531.53,
      y: 497.42,
      w: 16.46,
      h: 10.58,
      label: '',
      name: 'Service Corridor (aft)',
      size: 0,
      at: [539.8, 502.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-burial-passage',
      tier: 'tier-1',
      region: null,
      x: 397.45,
      y: 195.31,
      w: 13.08,
      h: 11.76,
      label: '',
      name: 'Burial Chamber Passage',
      size: 0,
      at: [404.0, 201.2],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-queens-living-quarters-room-01',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 334.05,
      y: 169.22,
      w: 19.75,
      h: 7.05,
      label: '',
      name: "Queen's Room 01",
      size: 0,
      at: [343.9, 172.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-02',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 367.78,
      y: 169.22,
      w: 19.75,
      h: 7.05,
      label: '',
      name: "Queen's Room 02",
      size: 0,
      at: [377.7, 172.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-03',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 334.05,
      y: 169.22,
      w: 19.75,
      h: 7.05,
      label: '',
      name: "Queen's Room 03",
      size: 0,
      at: [343.9, 172.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-04',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 367.78,
      y: 169.22,
      w: 19.75,
      h: 7.05,
      label: '',
      name: "Queen's Room 04",
      size: 0,
      at: [377.7, 172.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-05',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 334.05,
      y: 169.22,
      w: 19.75,
      h: 7.05,
      label: '',
      name: "Queen's Room 05",
      size: 0,
      at: [343.9, 172.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-06',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 367.78,
      y: 169.22,
      w: 19.75,
      h: 7.05,
      label: '',
      name: "Queen's Room 06",
      size: 0,
      at: [377.7, 172.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-07',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 334.05,
      y: 169.22,
      w: 19.75,
      h: 7.05,
      label: '',
      name: "Queen's Room 07",
      size: 0,
      at: [343.9, 172.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-08',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 367.78,
      y: 169.22,
      w: 19.75,
      h: 7.05,
      label: '',
      name: "Queen's Room 08",
      size: 0,
      at: [377.7, 172.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-corridor',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 353.8,
      y: 169.22,
      w: 13.98,
      h: 7.05,
      label: '',
      name: "Queens' Quarters Corridor",
      size: 0,
      at: [360.8, 172.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-vvip-corridor',
      tier: 'tier-1',
      region: 'vvip-living-quarters',
      x: 250.58,
      y: 195.31,
      w: 7.06,
      h: 11.76,
      label: '',
      name: 'VVIP Block Corridor',
      size: 0,
      at: [254.1, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-corridor-starboard',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 499.79,
      y: 195.31,
      w: 7.06,
      h: 11.76,
      label: '',
      name: "Guards' Round (starboard)",
      size: 0,
      at: [503.3, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-corridor-port',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 391.65,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: "Guards' Round (port)",
      size: 0,
      at: [395.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1001',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 492.74,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Approach — Door 1',
      size: 0,
      at: [496.3, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1002',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Approach — Door 2',
      size: 0,
      at: [402.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1003',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 492.74,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Approach — Door 3',
      size: 0,
      at: [496.3, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1004',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Approach — Door 4',
      size: 0,
      at: [402.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1005',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 492.74,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Approach — Door 5',
      size: 0,
      at: [496.3, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1006',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Approach — Door 6',
      size: 0,
      at: [402.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1007',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 492.74,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Approach — Door 7',
      size: 0,
      at: [496.3, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1008',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Approach — Door 8',
      size: 0,
      at: [402.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1009',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 492.74,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Approach — Door 9',
      size: 0,
      at: [496.3, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1010',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Approach — Door 10',
      size: 0,
      at: [402.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1011',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 492.74,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Approach — Door 11',
      size: 0,
      at: [496.3, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1012',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Approach — Door 12',
      size: 0,
      at: [402.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1013',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 492.74,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Approach — Door 13',
      size: 0,
      at: [496.3, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1014',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 398.7,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Approach — Door 14',
      size: 0,
      at: [402.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-1',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 445.72,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Back Passage 1',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-2',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 445.72,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Back Passage 2',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-3',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 445.72,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Back Passage 3',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-4',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 445.72,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Back Passage 4',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-5',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 445.72,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Back Passage 5',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-6',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 445.72,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Back Passage 6',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-7',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 445.72,
      y: 195.31,
      w: 7.05,
      h: 11.76,
      label: '',
      name: 'Back Passage 7',
      size: 0,
      at: [449.2, 201.2],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-c-port-corridor',
      tier: 'tier-1-c',
      region: null,
      x: 329.93,
      y: 169.22,
      w: 4.12,
      h: 7.05,
      label: '',
      name: 'Port Corridor',
      size: 0,
      at: [332.0, 172.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-warehouse',
      tier: 'tier-5',
      region: 't5-warehouses',
      x: 342.28,
      y: 479.79,
      w: 263.31,
      h: 28.21,
      label: 'Cha-R-Controlled Warehouse',
      name: 'Cha-R-Controlled Warehouse',
      size: 11,
      at: [473.9, 497.6],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-observation-deck',
      tier: 'tier-3',
      region: 't3-obs-deck',
      x: 539.76,
      y: 338.73,
      w: 141.38,
      h: 21.16,
      label: 'Observation Deck',
      name: 'Observation Deck',
      size: 11,
      at: [610.5, 353.0],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-residential-standard',
      tier: 'tier-3',
      region: 't3-residential-ord',
      x: 161.25,
      y: 345.78,
      w: 148.11,
      h: 14.11,
      label: 'Standard Residential Block',
      name: 'Standard Residential Block',
      size: 8,
      at: [235.3, 355.5],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-main-corridor',
      tier: 'tier-1',
      region: null,
      x: 218.85,
      y: 195.31,
      w: 172.8,
      h: 11.76,
      label: 'Main Corridor (port)',
      name: 'Main Corridor (port)',
      size: 8,
      at: [305.2, 203.9],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-standard-cabins',
      tier: 'tier-5',
      region: 't5-residential',
      x: 161.25,
      y: 497.42,
      w: 148.11,
      h: 10.58,
      label: '',
      name: 'Tier 5 Standard Cabins (forward)',
      size: 0,
      at: [235.3, 502.7],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-ei-i-family-office',
      tier: 'tier-4',
      region: 'tier-4-ei-i-family-office',
      x: 408.1,
      y: 423.36,
      w: 143.89,
      h: 10.58,
      label: '',
      name: 'Ei-I Family Office',
      size: 0,
      at: [480.0, 428.6],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-starboard-promenade',
      tier: 'tier-3',
      region: null,
      x: 681.14,
      y: 345.78,
      w: 105.48,
      h: 14.11,
      label: 'Starboard Promenade',
      name: 'Starboard Promenade',
      size: 8,
      at: [733.9, 355.5],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-xi-yu-family-office',
      tier: 'tier-4',
      region: 't4-xiyu',
      x: 276.45,
      y: 423.36,
      w: 131.65,
      h: 10.58,
      label: '',
      name: 'Xi-Yu Family Office',
      size: 0,
      at: [342.3, 428.6],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-princes-quarters-gate',
      tier: 'tier-1',
      region: null,
      x: 391.65,
      y: 195.31,
      w: 115.2,
      h: 11.76,
      label: "Princes' Quarters Gate",
      name: "Princes' Quarters Gate",
      size: 8,
      at: [449.2, 203.9],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-west-mid',
      tier: 'tier-4',
      region: null,
      x: 144.79,
      y: 423.36,
      w: 115.2,
      h: 10.58,
      label: '',
      name: 'West General Area (midships)',
      size: 0,
      at: [202.4, 428.6],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-east',
      tier: 'tier-4',
      region: null,
      x: 564.45,
      y: 423.36,
      w: 115.2,
      h: 10.58,
      label: '',
      name: 'East General Area',
      size: 0,
      at: [622.0, 428.6],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-detention-void',
      tier: 'tier-1',
      region: null,
      x: 613.82,
      y: 195.31,
      w: 98.74,
      h: 11.76,
      label: '',
      name: 'Starboard Forward Floor',
      size: 0,
      at: [663.2, 201.2],
      cut: true,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-4-starboard-promenade',
      tier: 'tier-4',
      region: null,
      x: 679.65,
      y: 423.36,
      w: 106.97,
      h: 10.58,
      label: '',
      name: 'Starboard Promenade',
      size: 0,
      at: [733.1, 428.6],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-port-promenade',
      tier: 'tier-1',
      region: null,
      x: 136.56,
      y: 195.31,
      w: 82.29,
      h: 11.76,
      label: 'Port Promenade',
      name: 'Port Promenade',
      size: 8,
      at: [177.7, 203.9],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-main-corridor-starboard',
      tier: 'tier-1',
      region: null,
      x: 506.85,
      y: 195.31,
      w: 82.28,
      h: 11.76,
      label: '',
      name: 'Main Corridor (starboard)',
      size: 0,
      at: [548.0, 201.2],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-port-promenade',
      tier: 'tier-2',
      region: null,
      x: 136.56,
      y: 270.55,
      w: 82.29,
      h: 11.75,
      label: 'Port Promenade',
      name: 'Port Promenade',
      size: 8,
      at: [177.7, 279.1],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-port-promenade',
      tier: 'tier-3',
      region: null,
      x: 95.42,
      y: 345.78,
      w: 65.83,
      h: 14.11,
      label: 'Port Promenade',
      name: 'Port Promenade',
      size: 8,
      at: [128.3, 355.5],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-starboard-promenade',
      tier: 'tier-2',
      region: null,
      x: 671.42,
      y: 270.55,
      w: 65.83,
      h: 11.75,
      label: '',
      name: 'Starboard Promenade',
      size: 0,
      at: [704.3, 276.4],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-port-promenade',
      tier: 'tier-5',
      region: null,
      x: 95.42,
      y: 497.42,
      w: 65.83,
      h: 10.58,
      label: '',
      name: 'Port Promenade',
      size: 0,
      at: [128.3, 502.7],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-starboard-promenade',
      tier: 'tier-5',
      region: null,
      x: 605.59,
      y: 497.42,
      w: 65.83,
      h: 10.58,
      label: '',
      name: 'Starboard Promenade',
      size: 0,
      at: [638.5, 502.7],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-central-spine',
      tier: 'tier-3',
      region: null,
      x: 309.36,
      y: 345.78,
      w: 32.92,
      h: 14.11,
      label: '',
      name: 'Central Spine',
      size: 0,
      at: [325.8, 352.8],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-starboard-corridor',
      tier: 'tier-3',
      region: null,
      x: 506.85,
      y: 345.78,
      w: 32.91,
      h: 14.11,
      label: '',
      name: 'Starboard Corridor',
      size: 0,
      at: [523.3, 352.8],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-main-corridor',
      tier: 'tier-5',
      region: null,
      x: 309.36,
      y: 497.42,
      w: 32.92,
      h: 10.58,
      label: '',
      name: 'Main Corridor',
      size: 0,
      at: [325.8, 502.7],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-lifeboats-port',
      tier: 'tier-1',
      region: 'lifeboats',
      x: 111.87,
      y: 195.31,
      w: 24.69,
      h: 11.76,
      label: '',
      name: 'Lifeboat Deck (port)',
      size: 0,
      at: [124.2, 201.2],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-lifeboats-starboard',
      tier: 'tier-1',
      region: 'lifeboats',
      x: 712.56,
      y: 195.31,
      w: 24.69,
      h: 11.76,
      label: '',
      name: 'Lifeboat Deck (starboard)',
      size: 0,
      at: [724.9, 201.2],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-starboard-corridor',
      tier: 'tier-1',
      region: null,
      x: 589.13,
      y: 195.31,
      w: 24.69,
      h: 11.76,
      label: '',
      name: 'Starboard Corridor',
      size: 0,
      at: [601.5, 201.2],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-port-corridor',
      tier: 'tier-4',
      region: null,
      x: 120.1,
      y: 423.36,
      w: 24.69,
      h: 10.58,
      label: '',
      name: 'Port Corridor',
      size: 0,
      at: [132.4, 428.6],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-b-starboard-corridor',
      tier: 'tier-1-b',
      region: null,
      x: 589.13,
      y: 177.45,
      w: 24.69,
      h: 7.05,
      label: '',
      name: 'Starboard Corridor',
      size: 0,
      at: [601.5, 181.0],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-starboard-corridor',
      tier: 'tier-4',
      region: null,
      x: 552.1,
      y: 423.36,
      w: 12.35,
      h: 10.58,
      label: '',
      name: 'Starboard Corridor',
      size: 0,
      at: [558.3, 428.6],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-jail-block-walkway',
      tier: 'tier-1-b',
      region: null,
      x: 700.22,
      y: 177.45,
      w: 12.34,
      h: 7.05,
      label: '',
      name: 'Jail Block Walkway',
      size: 0,
      at: [706.4, 181.0],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-jail-block-hall',
      tier: 'tier-1-b',
      region: null,
      x: 613.82,
      y: 177.45,
      w: 12.34,
      h: 7.05,
      label: '',
      name: 'Jail Block Hall',
      size: 0,
      at: [620.0, 181.0],
      cut: true,
      through: true,
      inferred: true,
    },
  ]

  /**
   * A deck of the tier-1 liner is labelled to starboard and on one line: three
   * tiers-worth of tab on the port margin, three and a half metres apart, is
   * three labels written over each other.
   */
  const decks = [
    {
      id: 'tier-1-c',
      name: 'Tier 1 · Guest Deck',
      nameFr: 'Pont 1 · Pont des hôtes',
      child: true,
      x0: 281.74,
      x1: 620.87,
      floor: 176.27,
      ceiling: 169.22,
      elevation: 141.1,
    },
    {
      id: 'tier-1-b',
      name: 'Tier 1 · Garrison Deck',
      nameFr: 'Pont 1 · Pont de la garnison',
      child: true,
      x0: 503.91,
      x1: 712.56,
      floor: 184.5,
      ceiling: 177.45,
      elevation: 137.6,
    },
    {
      id: 'tier-1',
      name: 'Tier 1',
      nameFr: 'Pont 1',
      child: false,
      x0: 126.29,
      x1: 712.56,
      floor: 207.07,
      ceiling: 195.31,
      elevation: 128,
    },
    {
      id: 'tier-2',
      name: 'Tier 2',
      nameFr: 'Pont 2',
      child: false,
      x0: 85.14,
      x1: 753.71,
      floor: 282.3,
      ceiling: 270.55,
      elevation: 96,
    },
    {
      id: 'tier-3',
      name: 'Tier 3',
      nameFr: 'Pont 3',
      child: false,
      x0: 44.0,
      x1: 792.8,
      floor: 359.89,
      ceiling: 345.78,
      elevation: 63,
    },
    {
      id: 'tier-4',
      name: 'Tier 4',
      nameFr: 'Pont 4',
      child: false,
      x0: 50.16,
      x1: 786.62,
      floor: 433.94,
      ceiling: 423.36,
      elevation: 31.5,
    },
    {
      id: 'tier-5',
      name: 'Tier 5',
      nameFr: 'Pont 5',
      child: false,
      x0: 76.04,
      x1: 690.8,
      floor: 508.0,
      ceiling: 497.42,
      elevation: 0,
    },
  ]

  /**
   * A deck carries both of its names, because the tabs are the only labels on
   * the section that come from the ship's own data rather than the dictionary,
   * and a single name means one of the two languages reads the other's.
   */
  const deckName = (deck: { name: string; nameFr: string }) =>
    $locale === 'fr' ? deck.nameFr : deck.name

  const gaps = [
    {
      id: 'tier-5-tier-4',
      x: 76.04,
      y: 433.94,
      w: 614.76,
      h: 63.48,
      metres: 27.0,
    },
    {
      id: 'tier-4-tier-3',
      x: 50.16,
      y: 359.89,
      w: 736.46,
      h: 63.47,
      metres: 27.0,
    },
    {
      id: 'tier-3-tier-2',
      x: 85.14,
      y: 282.3,
      w: 668.57,
      h: 63.48,
      metres: 27,
    },
    {
      id: 'tier-2-tier-1',
      x: 126.29,
      y: 207.07,
      w: 586.27,
      h: 63.48,
      metres: 27,
    },
    {
      id: 'tier-1-tier-1-b',
      x: 503.91,
      y: 184.5,
      w: 208.65,
      h: 10.81,
      metres: 4.6,
    },
  ]

  /**
   * The liner over tier 1: the decks of it the reconstruction does not hold,
   * stepping back as they rise the way the ch. 369 exterior shows them.
   *
   * How many there are is the ship's own arithmetic — 41 decks, seven held,
   * the rest spent in the bands between the tiers, and what is left over stands
   * up here. How far each one steps back is not: nothing draws the plan of a
   * terrace, so they recede evenly to a third of the deck below them and carry
   * the same hatch as every other deck nobody has drawn.
   */
  const terraces = [
    {
      x: 294.3,
      y: 158.64,
      w: 314.01,
      h: 10.58,
    },
    {
      x: 306.86,
      y: 148.06,
      w: 288.89,
      h: 10.58,
    },
    {
      x: 319.42,
      y: 137.48,
      w: 263.77,
      h: 10.58,
    },
    {
      x: 331.98,
      y: 126.9,
      w: 238.65,
      h: 10.58,
    },
    {
      x: 344.54,
      y: 116.32,
      w: 213.53,
      h: 10.58,
    },
    {
      x: 357.1,
      y: 105.74,
      w: 188.41,
      h: 10.58,
    },
    {
      x: 369.66,
      y: 95.16,
      w: 163.29,
      h: 10.58,
    },
    {
      x: 382.22,
      y: 84.58,
      w: 138.17,
      h: 10.58,
    },
    {
      x: 394.78,
      y: 74.0,
      w: 113.05,
      h: 10.58,
    },
  ]

  /** Where the note about the liner sits: on its widest, lowest step. */
  const superstructure = {
    x: 294.3,
    y: 74.0,
    w: 314.01,
    h: 95.22,
    decks: 9,
  }

  const waterline = 395.15

  /**
   * A room on the section opens the deck it belongs to and then itself, which
   * is the same two steps a reader takes by hand: the section is the way in to
   * a deck, not a replacement for it.
   */
  function open(room: Room) {
    mapState.selectTier(room.tier)
    if (room.region) mapState.selectLocation(room.region)
  }

  function openWithKeyboard(event: KeyboardEvent, room: Room) {
    if (event.key !== 'Enter' && event.key !== ' ') return
    event.preventDefault()
    event.stopPropagation()
    open(room)
  }

  function openDeck(tierId: string) {
    mapState.selectTier(tierId)
  }

  function openDeckWithKeyboard(event: KeyboardEvent, tierId: string) {
    if (event.key !== 'Enter' && event.key !== ' ') return
    event.preventDefault()
    openDeck(tierId)
  }
</script>

<svg viewBox="0 0 1000 600" class="w-full h-full text-[#FFFFF0]">
  <defs>
    <style>
      .sea {
        fill: #0f172a;
      }
      .hull {
        fill: #1a0f0f;
        stroke: #ffd700;
        stroke-width: 3;
      }
      .room {
        fill: #2a1515;
        stroke: #fffff0;
        stroke-width: 1;
        transition: fill 0.2s;
      }
      .room.behind {
        fill: #221010;
        stroke: #fffff0;
        stroke-opacity: 0.18;
        stroke-width: 0.5;
        fill-opacity: 0.55;
      }
      .room.clickable {
        cursor: pointer;
      }
      .room.clickable:hover {
        fill: #3d1c1c;
      }
      g[role='button']:focus .room {
        stroke: #ffd700;
        stroke-width: 2;
      }
      .room.through {
        fill: #150b0b;
        stroke: #ffd700;
        stroke-opacity: 0.35;
        stroke-dasharray: 4 4;
      }
      .room.inferred {
        fill: #16171c;
        stroke: #9dc4e0;
        stroke-opacity: 0.4;
      }
      .gap {
        fill: url(#unbuilt);
        stroke: #ffd700;
        stroke-opacity: 0.12;
        stroke-width: 0.5;
      }
      .deck-rule {
        stroke: #ffd700;
        stroke-opacity: 0.45;
        stroke-width: 1;
        stroke-dasharray: 2 5;
      }
      .deck-tab {
        cursor: pointer;
      }
      .deck-tab text {
        fill: #ffd700;
        font-family: sans-serif;
        font-size: 12px;
        letter-spacing: 1px;
      }
      .deck-tab:hover text {
        fill: #fffff0;
      }
      .label {
        fill: #fffff0;
        font-family: sans-serif;
        pointer-events: none;
        text-anchor: middle;
      }
      .note {
        fill: #fffff0;
        fill-opacity: 0.5;
        font-family: sans-serif;
        font-size: 10px;
        pointer-events: none;
      }
      .waterline {
        stroke: #9dc4e0;
        stroke-opacity: 0.55;
        stroke-width: 1.5;
        stroke-dasharray: 8 6;
      }
    </style>
    <pattern
      id="unbuilt"
      width="6"
      height="6"
      patternTransform="rotate(45)"
      patternUnits="userSpaceOnUse"
    >
      <rect width="6" height="6" fill="#140d0d" />
      <line x1="0" y1="0" x2="0" y2="6" stroke="#ffd700" stroke-opacity="0.13" stroke-width="1.5" />
    </pattern>
  </defs>

  <rect class="sea" x="0" y={waterline} width="1000" height={600 - waterline} />

  <polygon
    class="hull"
    points="76.04,508.0 76.04,497.42 50.16,433.94 50.16,423.36 44.0,359.89 44.0,345.78 85.14,282.3 85.14,270.55 126.29,207.07 126.29,195.31 503.91,184.5 503.91,177.45 281.74,176.27 281.74,169.22 294.3,169.22 294.3,158.64 306.86,158.64 306.86,148.06 319.42,148.06 319.42,137.48 331.98,137.48 331.98,126.9 344.54,126.9 344.54,116.32 357.1,116.32 357.1,105.74 369.66,105.74 369.66,95.16 382.22,95.16 382.22,84.58 394.78,84.58 394.78,74.0 507.83,74.0 507.83,84.58 520.39,84.58 520.39,95.16 532.95,95.16 532.95,105.74 545.51,105.74 545.51,116.32 558.07,116.32 558.07,126.9 570.63,126.9 570.63,137.48 583.19,137.48 583.19,148.06 595.75,148.06 595.75,158.64 608.31,158.64 608.31,169.22 620.87,169.22 620.87,176.27 712.56,177.45 712.56,184.5 712.56,195.31 712.56,207.07 753.71,270.55 753.71,282.3 792.8,345.78 792.8,359.89 786.62,423.36 786.62,433.94 690.8,497.42 690.8,508.0"
  />

  {#each terraces as terrace, i (i)}
    <rect class="gap" x={terrace.x} y={terrace.y} width={terrace.w} height={terrace.h} />
  {/each}

  {#each gaps as gap (gap.id)}
    <rect class="gap" x={gap.x} y={gap.y} width={gap.w} height={gap.h} />
  {/each}

  <g id="section-rooms">
    {#each rooms as room (room.id)}
      {#if room.cut && room.region}
        <g
          role="button"
          tabindex="0"
          aria-label={room.name}
          onclick={() => open(room)}
          onkeydown={(event) => openWithKeyboard(event, room)}
        >
          <title>{room.name}</title>
          <rect
            class="room clickable"
            class:through={room.through}
            class:inferred={room.inferred}
            x={room.x}
            y={room.y}
            width={room.w}
            height={room.h}
          />
        </g>
      {:else}
        <rect
          class="room"
          class:behind={!room.cut}
          class:through={room.through}
          class:inferred={room.inferred}
          x={room.x}
          y={room.y}
          width={room.w}
          height={room.h}
        />
      {/if}
    {/each}

    {#each rooms.filter((room) => room.size > 0) as room (room.id)}
      <text class="label" x={room.at[0]} y={room.at[1]} font-size={room.size}>{room.label}</text>
    {/each}
  </g>

  <line class="waterline" x1="0" y1={waterline} x2="1000" y2={waterline} />

  <!-- The eye of the ch. 349 page: low, forward, and opening nothing. -->
  <circle
    cx="118.93"
    cy="378.69"
    r="11.8"
    fill="#050505"
    stroke="#ffd700"
    stroke-width="2"
    pointer-events="none"
  />
  <circle cx="118.93" cy="378.69" r="4.5" fill="#fffff0" pointer-events="none" />

  {#each decks as deck (deck.id)}
    <line class="deck-rule" x1={deck.x0} y1={deck.floor} x2={deck.x1} y2={deck.floor} />
    <g
      class="deck-tab"
      role="button"
      tabindex="0"
      aria-label={deckName(deck)}
      onclick={() => openDeck(deck.id)}
      onkeydown={(event) => openDeckWithKeyboard(event, deck.id)}
    >
      {#if deck.child}
        <text x="1000" y={deck.ceiling + 11} text-anchor="end" font-size="10"
          >{deckName(deck)} · {deck.elevation} m</text
        >
      {:else}
        <text x="6" y={deck.ceiling + 12}>{deckName(deck)}</text>
        <text x="6" y={deck.ceiling + 25} font-size="9" fill-opacity="0.55">{deck.elevation} m</text
        >
      {/if}
    </g>
  {/each}

  {#each gaps as gap (gap.id)}
    {#if gap.h > 26}
      <text class="note" x={gap.x + gap.w / 2} y={gap.y + gap.h / 2 + 3} text-anchor="middle"
        >{$t.ship.unmodelledDecks(gap.metres)}</text
      >
    {/if}
  {/each}

  <text
    class="note"
    x={superstructure.x + superstructure.w / 2}
    y={superstructure.y - 8}
    text-anchor="middle">{$t.ship.superstructure(superstructure.decks)}</text
  >
</svg>
