<script lang="ts">
  /**
   * The Black Whale in longitudinal section, generated from
   * `data/ship/blueprint.json` by `scripts/generate-section-map.py`.
   *
   * Cut on the centreline, looking to starboard, bow to the left — the view of
   * the ch. 349 double page, drawn from the reconstruction instead of traced.
   * One unit is 0.3492 m; the section has its own scale because 175 m of ship
   * and 77 m of freeboard do not fit the deck plans' 0.35 m per unit.
   *
   * Rooms the cut passes through are solid, labelled where the label fits, and
   * open their deck. Rooms it passes beside — everything to port or starboard —
   * are drawn behind and dim: they are what fills the ship, and on the manga
   * page they are the strips of texture between the labelled callouts.
   *
   * The banded gaps are the decks this reconstruction does not hold. The ship
   * has 41 of them and the tour walks 5, so about thirteen metres of ship sit
   * between each pair. Nothing is drawn inside them, because nothing is known
   * to be.
   *
   * The band over tier 1 is the same admission, and it is open at the top: the
   * ch. 369 exterior shows a liner terraced a dozen levels above the one floor
   * of it anyone has drawn a plan for. Closing that band at a height would be a
   * claim about how tall the liner is, and the page gives its shape, not its
   * scale.
   *
   * Do not hand-edit — regenerate from the blueprint.
   */
  import { mapState } from '$lib/state/mapState.svelte'
  import { locale, t } from '$lib/i18n'

  type Room = {
    id: string
    tier: string
    region: string | null
    x: number
    y: number
    w: number
    h: number
    label: string
    name: string
    size: number
    at: [number, number]
    cut: boolean
    through: boolean
    inferred: boolean
  }

  const rooms: Room[] = [
    {
      id: 'tier-4-recycling-sewage-facilities',
      tier: 'tier-4',
      region: 't4-recycling',
      x: 126.67,
      y: 394.89,
      w: 731.6,
      h: 22.91,
      label: '',
      name: 'Recycling & Sewage Facilities',
      size: 0,
      at: [492.5, 406.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-technical-recycling',
      tier: 'tier-5',
      region: 't4-recycling',
      x: 156.73,
      y: 485.09,
      w: 601.32,
      h: 22.91,
      label: '',
      name: 'Technical & Recycling Level',
      size: 0,
      at: [457.4, 496.5],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-forward-corridor',
      tier: 'tier-3',
      region: null,
      x: 156.73,
      y: 310.42,
      w: 681.5,
      h: 17.18,
      label: '',
      name: 'Forward Corridor',
      size: 0,
      at: [497.5, 319.0],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-aft-corridor',
      tier: 'tier-3',
      region: null,
      x: 156.73,
      y: 310.42,
      w: 681.5,
      h: 17.18,
      label: '',
      name: 'Aft Corridor',
      size: 0,
      at: [497.5, 319.0],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-king-living-quarters',
      tier: 'tier-1',
      region: 'king-quarters',
      x: 206.84,
      y: 121.44,
      w: 551.21,
      h: 20.04,
      label: '',
      name: "King's Living Quarters",
      size: 0,
      at: [482.4, 131.5],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-2-bulkhead',
      tier: 'tier-2',
      region: 't2-security',
      x: 156.73,
      y: 218.79,
      w: 701.54,
      h: 14.32,
      label: '',
      name: 'Tier 2 Bulkhead',
      size: 0,
      at: [507.5, 225.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-banquet-hall',
      tier: 'tier-1',
      region: 'banquet-hall',
      x: 256.95,
      y: 115.71,
      w: 382.27,
      h: 25.77,
      label: '',
      name: 'Banquet Hall',
      size: 0,
      at: [448.1, 128.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-forward-corridor',
      tier: 'tier-4',
      region: null,
      x: 136.69,
      y: 404.92,
      w: 721.58,
      h: 12.88,
      label: '',
      name: 'Forward Corridor',
      size: 0,
      at: [497.5, 411.4],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-aft-corridor',
      tier: 'tier-4',
      region: null,
      x: 166.75,
      y: 404.92,
      w: 691.52,
      h: 12.88,
      label: '',
      name: 'Aft Corridor',
      size: 0,
      at: [512.5, 411.4],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-forward-corridor',
      tier: 'tier-2',
      region: null,
      x: 256.95,
      y: 218.79,
      w: 551.21,
      h: 14.32,
      label: '',
      name: 'Forward Corridor',
      size: 0,
      at: [532.6, 225.9],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-main-corridor',
      tier: 'tier-2',
      region: null,
      x: 256.95,
      y: 218.79,
      w: 551.21,
      h: 14.32,
      label: '',
      name: 'Main Corridor',
      size: 0,
      at: [532.6, 225.9],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-aft-corridor',
      tier: 'tier-2',
      region: null,
      x: 256.95,
      y: 218.79,
      w: 551.21,
      h: 14.32,
      label: '',
      name: 'Aft Corridor',
      size: 0,
      at: [532.6, 225.9],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-aft-corridor',
      tier: 'tier-5',
      region: null,
      x: 166.75,
      y: 495.11,
      w: 601.32,
      h: 12.89,
      label: '',
      name: 'Aft Corridor',
      size: 0,
      at: [467.4, 501.6],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-screening-room',
      tier: 'tier-2',
      region: 't2-screening-room',
      x: 256.95,
      y: 204.48,
      w: 250.55,
      h: 28.63,
      label: '',
      name: 'Screening Room',
      size: 0,
      at: [382.2, 218.8],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-forward-corridor',
      tier: 'tier-5',
      region: null,
      x: 186.8,
      y: 495.11,
      w: 541.19,
      h: 12.89,
      label: '',
      name: 'Forward Corridor',
      size: 0,
      at: [457.4, 501.6],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-royal-approach',
      tier: 'tier-1',
      region: null,
      x: 256.95,
      y: 127.16,
      w: 450.99,
      h: 14.32,
      label: '',
      name: 'Banquet Hall Vestibule',
      size: 0,
      at: [482.4, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-aft-promenade',
      tier: 'tier-1',
      region: null,
      x: 256.95,
      y: 127.16,
      w: 450.99,
      h: 14.32,
      label: '',
      name: 'Aft Promenade',
      size: 0,
      at: [482.4, 134.3],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-central-passage',
      tier: 'tier-4',
      region: 'tier-4-central-passage',
      x: 166.75,
      y: 404.92,
      w: 496.09,
      h: 12.88,
      label: '',
      name: 'Central Passage Tier 4–5',
      size: 0,
      at: [414.8, 411.4],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-4-secondary-passage',
      tier: 'tier-4',
      region: null,
      x: 166.75,
      y: 404.92,
      w: 496.09,
      h: 12.88,
      label: '',
      name: 'Secondary Transport Route',
      size: 0,
      at: [414.8, 411.4],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-5-transverse-corridor',
      tier: 'tier-5',
      region: null,
      x: 407.28,
      y: 495.11,
      w: 320.71,
      h: 12.89,
      label: '',
      name: 'Transverse Corridor',
      size: 0,
      at: [567.6, 501.6],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-central-hospital',
      tier: 'tier-3',
      region: 't3-hospital',
      x: 407.28,
      y: 310.42,
      w: 200.44,
      h: 17.18,
      label: '',
      name: 'Central Hospital',
      size: 0,
      at: [507.5, 319.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-cineplex',
      tier: 'tier-3',
      region: 't3-cinema',
      x: 647.81,
      y: 304.7,
      w: 150.33,
      h: 22.9,
      label: '',
      name: 'Cineplex',
      size: 0,
      at: [723.0, 316.1],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-c-aft-passage',
      tier: 'tier-1-c',
      region: null,
      x: 342.14,
      y: 95.38,
      w: 395.87,
      h: 8.59,
      label: '',
      name: 'Aft Passage',
      size: 0,
      at: [540.1, 99.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-vip-quarters',
      tier: 'tier-2',
      region: null,
      x: 256.95,
      y: 218.79,
      w: 220.49,
      h: 14.32,
      label: '',
      name: 'VIP Quarters',
      size: 0,
      at: [367.2, 225.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-residential-first-class',
      tier: 'tier-3',
      region: 't3-residential-1st',
      x: 186.8,
      y: 310.42,
      w: 180.39,
      h: 17.18,
      label: '',
      name: 'First-Class Residential Block',
      size: 0,
      at: [277.0, 319.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-supreme-court',
      tier: 'tier-1-b',
      region: 'supreme-court',
      x: 738.01,
      y: 91.09,
      w: 120.26,
      h: 22.9,
      label: '',
      name: 'Supreme Court',
      size: 0,
      at: [798.1, 102.5],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-2-ministry-of-justice',
      tier: 'tier-2',
      region: 't2-justice',
      x: 527.55,
      y: 218.79,
      w: 180.39,
      h: 14.32,
      label: '',
      name: 'Ministry of Justice',
      size: 0,
      at: [617.7, 225.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-heilly-family-office',
      tier: 'tier-3',
      region: 't3-heilly',
      x: 647.81,
      y: 310.42,
      w: 150.33,
      h: 17.18,
      label: '',
      name: 'Heil-Ly Family Office',
      size: 0,
      at: [723.0, 319.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-standard-cabins-aft',
      tier: 'tier-5',
      region: 't5-residential',
      x: 186.8,
      y: 495.11,
      w: 180.39,
      h: 12.89,
      label: '',
      name: 'Tier 5 Standard Cabins (aft)',
      size: 0,
      at: [277.0, 501.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-central-dining-hall',
      tier: 'tier-5',
      region: 'central-dining-hall',
      x: 547.59,
      y: 482.23,
      w: 90.2,
      h: 25.77,
      label: '',
      name: 'Central Dining Hall',
      size: 0,
      at: [592.7, 495.1],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-central-courthouse',
      tier: 'tier-3',
      region: 'central-courthouse',
      x: 507.5,
      y: 304.7,
      w: 100.22,
      h: 22.9,
      label: '',
      name: 'Central Courthouse',
      size: 0,
      at: [557.6, 316.1],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-center-north',
      tier: 'tier-4',
      region: null,
      x: 327.11,
      y: 404.92,
      w: 160.35,
      h: 12.88,
      label: '',
      name: 'Central General Area (forward)',
      size: 0,
      at: [407.3, 411.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-center-south',
      tier: 'tier-4',
      region: null,
      x: 327.11,
      y: 404.92,
      w: 160.35,
      h: 12.88,
      label: '',
      name: 'Central General Area (aft)',
      size: 0,
      at: [407.3, 411.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-corridor-aft',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 467.41,
      y: 127.16,
      w: 140.31,
      h: 14.32,
      label: '',
      name: "Guards' Round (aft)",
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-4-royal-army-conference-room',
      tier: 'tier-4',
      region: 'royal-army-office',
      x: 507.5,
      y: 404.92,
      w: 150.33,
      h: 12.88,
      label: '',
      name: 'Kakin Royal Army Conference Room',
      size: 0,
      at: [582.7, 411.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-medical-clinic',
      tier: 'tier-4',
      region: null,
      x: 507.5,
      y: 404.92,
      w: 150.33,
      h: 12.88,
      label: '',
      name: 'Tier 4 Medical Clinic',
      size: 0,
      at: [582.7, 411.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-banquet-hall-service-end',
      tier: 'tier-1',
      region: 'banquet-hall',
      x: 639.22,
      y: 115.71,
      w: 68.72,
      h: 27.49,
      label: '',
      name: 'Banquet Hall (service end)',
      size: 0,
      at: [673.6, 129.5],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-west-north',
      tier: 'tier-4',
      region: null,
      x: 166.75,
      y: 404.92,
      w: 140.31,
      h: 12.88,
      label: '',
      name: 'West General Area (forward)',
      size: 0,
      at: [236.9, 411.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-west-south',
      tier: 'tier-4',
      region: null,
      x: 166.75,
      y: 404.92,
      w: 140.31,
      h: 12.88,
      label: '',
      name: 'West General Area (aft)',
      size: 0,
      at: [236.9, 411.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-1',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 123.13,
      h: 14.32,
      label: '',
      name: 'Cross Gap 1',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-2',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 123.13,
      h: 14.32,
      label: '',
      name: 'Cross Gap 2',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-3',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 123.13,
      h: 14.32,
      label: '',
      name: 'Cross Gap 3',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-4',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 123.13,
      h: 14.32,
      label: '',
      name: 'Cross Gap 4',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-5',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 123.13,
      h: 14.32,
      label: '',
      name: 'Cross Gap 5',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-6',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 123.13,
      h: 14.32,
      label: '',
      name: 'Cross Gap 6',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-7',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 123.13,
      h: 14.32,
      label: '',
      name: 'Cross Gap 7',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-8',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 123.13,
      h: 14.32,
      label: '',
      name: 'Cross Gap 8',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-court-void',
      tier: 'tier-1',
      region: null,
      x: 738.01,
      y: 127.16,
      w: 120.26,
      h: 14.32,
      label: '',
      name: 'Starboard Aft Floor',
      size: 0,
      at: [798.1, 134.3],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-3-central-police-station',
      tier: 'tier-3',
      region: 'central-police-station',
      x: 407.28,
      y: 310.42,
      w: 100.22,
      h: 17.18,
      label: '',
      name: 'Central Police Station',
      size: 0,
      at: [457.4, 319.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-residential-units',
      tier: 'tier-3',
      region: 'central-police-station',
      x: 407.28,
      y: 310.42,
      w: 100.22,
      h: 17.18,
      label: '',
      name: 'Central Police Dorm Room',
      size: 0,
      at: [457.4, 319.0],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-3-bulkhead-access',
      tier: 'tier-3',
      region: null,
      x: 457.39,
      y: 310.42,
      w: 100.22,
      h: 17.18,
      label: '',
      name: 'Emergency Bulkhead to Tier 2',
      size: 0,
      at: [507.5, 319.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-5-cha-r-family-office',
      tier: 'tier-5',
      region: 't5-char',
      x: 407.28,
      y: 495.11,
      w: 120.27,
      h: 12.89,
      label: '',
      name: 'Cha-R Family Office',
      size: 0,
      at: [467.4, 501.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-garrison-void',
      tier: 'tier-1',
      region: null,
      x: 612.73,
      y: 127.16,
      w: 95.21,
      h: 14.32,
      label: '',
      name: 'Starboard Quarters Floor',
      size: 0,
      at: [660.3, 134.3],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-2-vip-witness-protection-area',
      tier: 'tier-2',
      region: 't2-justice',
      x: 712.95,
      y: 218.79,
      w: 95.21,
      h: 14.32,
      label: '',
      name: 'VIP Witness Protection Area',
      size: 0,
      at: [760.6, 225.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vip-casino',
      tier: 'tier-1-c',
      region: 'casino',
      x: 342.14,
      y: 81.06,
      w: 50.11,
      h: 22.91,
      label: '',
      name: 'VIP Casino',
      size: 0,
      at: [367.2, 92.5],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-2-heilly-secret-hideout',
      tier: 'tier-2',
      region: 't2-vip',
      x: 482.45,
      y: 218.79,
      w: 75.16,
      h: 14.32,
      label: '',
      name: 'Heil-Ly Secret Hideout',
      size: 0,
      at: [520.0, 225.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-area-37564',
      tier: 'tier-5',
      region: 'room-37564',
      x: 236.91,
      y: 495.11,
      w: 80.17,
      h: 12.89,
      label: '',
      name: 'Area 37564',
      size: 0,
      at: [277.0, 501.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-hangar-entrance',
      tier: 'tier-5',
      region: 'tier-5-hangar-entrance',
      x: 727.99,
      y: 495.11,
      w: 80.17,
      h: 12.89,
      label: '',
      name: 'Hangar Entrance',
      size: 0,
      at: [768.1, 501.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-residential-room-3101',
      tier: 'tier-3',
      region: 'room-3101',
      x: 186.8,
      y: 310.42,
      w: 60.13,
      h: 17.18,
      label: '',
      name: 'Room 3101 (Heil-Ly Trap)',
      size: 0,
      at: [216.9, 319.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-void',
      tier: 'tier-1',
      region: null,
      x: 397.26,
      y: 127.16,
      w: 65.14,
      h: 14.32,
      label: '',
      name: 'Port Central Floor',
      size: 0,
      at: [429.8, 134.3],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-5-medical-clinic',
      tier: 'tier-5',
      region: 't5-medical-none',
      x: 657.83,
      y: 495.11,
      w: 70.16,
      h: 12.89,
      label: '',
      name: 'Tier 5 Medical Clinic',
      size: 0,
      at: [692.9, 501.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-soldiers-living-quarters',
      tier: 'tier-1-b',
      region: 'soldiers-living-quarters',
      x: 612.73,
      y: 105.4,
      w: 95.21,
      h: 8.59,
      label: '',
      name: "Soldiers' Living Quarters",
      size: 0,
      at: [660.3, 109.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-princes-burial-chamber',
      tier: 'tier-1',
      region: 'princes-burial-chamber',
      x: 459.65,
      y: 124.3,
      w: 45.59,
      h: 17.18,
      label: '',
      name: "Princes' Burial Chamber",
      size: 0,
      at: [482.4, 132.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-prison-beyond',
      tier: 'tier-1-b',
      region: 'beyond-cell',
      x: 753.04,
      y: 105.4,
      w: 90.2,
      h: 8.59,
      label: '',
      name: "Beyond Netero's Holding Cell",
      size: 0,
      at: [798.1, 109.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vip-jail',
      tier: 'tier-1-b',
      region: 'vip-detention',
      x: 753.04,
      y: 105.4,
      w: 90.2,
      h: 8.59,
      label: '',
      name: 'VIP Jail',
      size: 0,
      at: [798.1, 109.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-casino-void',
      tier: 'tier-1',
      region: null,
      x: 342.14,
      y: 127.16,
      w: 50.11,
      h: 14.32,
      label: '',
      name: 'Port Inner Floor',
      size: 0,
      at: [367.2, 134.3],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1001',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1001',
      x: 541.86,
      y: 127.16,
      w: 48.68,
      h: 14.32,
      label: '',
      name: 'Room 1001 (Benjamin)',
      size: 0,
      at: [566.2, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1002',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1002',
      x: 484.59,
      y: 127.16,
      w: 48.68,
      h: 14.32,
      label: '',
      name: 'Room 1002 (Camilla)',
      size: 0,
      at: [508.9, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1003',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1003',
      x: 541.86,
      y: 127.16,
      w: 48.68,
      h: 14.32,
      label: '',
      name: 'Room 1003 (Zhang Lei)',
      size: 0,
      at: [566.2, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1004',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1004',
      x: 484.59,
      y: 127.16,
      w: 48.68,
      h: 14.32,
      label: '',
      name: 'Room 1004 (Tserriednich)',
      size: 0,
      at: [508.9, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1005',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1005',
      x: 541.86,
      y: 127.16,
      w: 48.68,
      h: 14.32,
      label: '',
      name: 'Room 1005 (Tubeppa)',
      size: 0,
      at: [566.2, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1006',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1006',
      x: 484.59,
      y: 127.16,
      w: 48.68,
      h: 14.32,
      label: '',
      name: 'Room 1006 (Tyson)',
      size: 0,
      at: [508.9, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1007',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1007',
      x: 541.86,
      y: 127.16,
      w: 48.68,
      h: 14.32,
      label: '',
      name: 'Room 1007 (Luzurus)',
      size: 0,
      at: [566.2, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1008',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1008',
      x: 484.59,
      y: 127.16,
      w: 48.68,
      h: 14.32,
      label: '',
      name: 'Room 1008 (Salé-salé)',
      size: 0,
      at: [508.9, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1009',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1009',
      x: 541.86,
      y: 127.16,
      w: 48.68,
      h: 14.32,
      label: '',
      name: 'Room 1009 (Halkenburg)',
      size: 0,
      at: [566.2, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1010',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1010',
      x: 484.59,
      y: 127.16,
      w: 48.68,
      h: 14.32,
      label: '',
      name: 'Room 1010 (Kacho)',
      size: 0,
      at: [508.9, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1011',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1011',
      x: 541.86,
      y: 127.16,
      w: 48.68,
      h: 14.32,
      label: '',
      name: 'Room 1011 (Fugetsu)',
      size: 0,
      at: [566.2, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1012',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1012',
      x: 484.59,
      y: 127.16,
      w: 48.68,
      h: 14.32,
      label: '',
      name: 'Room 1012 (Momoze)',
      size: 0,
      at: [508.9, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1013',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1013',
      x: 541.86,
      y: 127.16,
      w: 48.68,
      h: 14.32,
      label: '',
      name: 'Room 1013 (Marayam)',
      size: 0,
      at: [566.2, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1014',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1014',
      x: 484.59,
      y: 127.16,
      w: 48.68,
      h: 14.32,
      label: '',
      name: 'Room 1014 (Woble)',
      size: 0,
      at: [508.9, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-cabin-cross-corridor-west',
      tier: 'tier-5',
      region: null,
      x: 186.8,
      y: 495.11,
      w: 50.11,
      h: 12.89,
      label: '',
      name: 'Cabin Cross Corridor (west)',
      size: 0,
      at: [211.9, 501.6],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-cabin-cross-corridor-east',
      tier: 'tier-5',
      region: null,
      x: 317.08,
      y: 495.11,
      w: 50.11,
      h: 12.89,
      label: '',
      name: 'Cabin Cross Corridor (east)',
      size: 0,
      at: [342.1, 501.6],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-tier-1-access',
      tier: 'tier-2',
      region: null,
      x: 510.51,
      y: 218.79,
      w: 44.1,
      h: 14.32,
      label: '',
      name: 'Tier 1 Stairwell',
      size: 0,
      at: [532.6, 225.9],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-vvip-restricted-royal-01',
      tier: 'tier-1',
      region: null,
      x: 256.95,
      y: 127.16,
      w: 38.66,
      h: 14.32,
      label: '',
      name: 'Restricted Royal Suite 1',
      size: 0,
      at: [276.3, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-restricted-royal-02',
      tier: 'tier-1',
      region: null,
      x: 256.95,
      y: 127.16,
      w: 38.66,
      h: 14.32,
      label: '',
      name: 'Restricted Royal Suite 2',
      size: 0,
      at: [276.3, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-suite-01',
      tier: 'tier-1',
      region: null,
      x: 256.95,
      y: 127.16,
      w: 38.66,
      h: 14.32,
      label: '',
      name: 'VVIP Suite 1',
      size: 0,
      at: [276.3, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-suite-02',
      tier: 'tier-1',
      region: null,
      x: 256.95,
      y: 127.16,
      w: 38.66,
      h: 14.32,
      label: '',
      name: 'VVIP Suite 2',
      size: 0,
      at: [276.3, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-suite-03',
      tier: 'tier-1',
      region: null,
      x: 304.2,
      y: 127.16,
      w: 32.93,
      h: 14.32,
      label: '',
      name: 'VVIP Suite 3',
      size: 0,
      at: [320.7, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-suite-04',
      tier: 'tier-1',
      region: null,
      x: 304.2,
      y: 127.16,
      w: 32.93,
      h: 14.32,
      label: '',
      name: 'VVIP Suite 4',
      size: 0,
      at: [320.7, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-mafia-suite',
      tier: 'tier-1',
      region: null,
      x: 304.2,
      y: 127.16,
      w: 32.93,
      h: 14.32,
      label: '',
      name: 'Mafia VVIP Suite',
      size: 0,
      at: [320.7, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-v5-suite',
      tier: 'tier-1',
      region: null,
      x: 304.2,
      y: 127.16,
      w: 32.93,
      h: 14.32,
      label: '',
      name: "V5 Politician's Suite",
      size: 0,
      at: [320.7, 134.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-service-corridor-forward',
      tier: 'tier-5',
      region: null,
      x: 527.55,
      y: 495.11,
      w: 20.04,
      h: 12.89,
      label: '',
      name: 'Passage to the Great Refectory',
      size: 0,
      at: [537.6, 501.6],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-5-service-corridor-aft',
      tier: 'tier-5',
      region: null,
      x: 637.79,
      y: 495.11,
      w: 20.04,
      h: 12.89,
      label: '',
      name: 'Service Corridor (aft)',
      size: 0,
      at: [647.8, 501.6],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-burial-passage',
      tier: 'tier-1',
      region: null,
      x: 474.49,
      y: 127.16,
      w: 15.92,
      h: 14.32,
      label: '',
      name: 'Burial Chamber Passage',
      size: 0,
      at: [482.5, 134.3],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-queens-living-quarters-room-01',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 397.26,
      y: 95.38,
      w: 24.05,
      h: 8.59,
      label: '',
      name: "Queen's Room 01",
      size: 0,
      at: [409.3, 99.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-02',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 438.35,
      y: 95.38,
      w: 24.05,
      h: 8.59,
      label: '',
      name: "Queen's Room 02",
      size: 0,
      at: [450.4, 99.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-03',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 397.26,
      y: 95.38,
      w: 24.05,
      h: 8.59,
      label: '',
      name: "Queen's Room 03",
      size: 0,
      at: [409.3, 99.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-04',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 438.35,
      y: 95.38,
      w: 24.05,
      h: 8.59,
      label: '',
      name: "Queen's Room 04",
      size: 0,
      at: [450.4, 99.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-05',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 397.26,
      y: 95.38,
      w: 24.05,
      h: 8.59,
      label: '',
      name: "Queen's Room 05",
      size: 0,
      at: [409.3, 99.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-06',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 438.35,
      y: 95.38,
      w: 24.05,
      h: 8.59,
      label: '',
      name: "Queen's Room 06",
      size: 0,
      at: [450.4, 99.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-07',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 397.26,
      y: 95.38,
      w: 24.05,
      h: 8.59,
      label: '',
      name: "Queen's Room 07",
      size: 0,
      at: [409.3, 99.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-08',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 438.35,
      y: 95.38,
      w: 24.05,
      h: 8.59,
      label: '',
      name: "Queen's Room 08",
      size: 0,
      at: [450.4, 99.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-corridor',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 421.31,
      y: 95.38,
      w: 17.04,
      h: 8.59,
      label: '',
      name: "Queens' Quarters Corridor",
      size: 0,
      at: [429.8, 99.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-vvip-corridor',
      tier: 'tier-1',
      region: 'vvip-living-quarters',
      x: 295.61,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'VVIP Block Corridor',
      size: 0,
      at: [299.9, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-corridor-port',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 467.41,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: "Guards' Round (port)",
      size: 0,
      at: [471.7, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-corridor-starboard',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 599.13,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: "Guards' Round (starboard)",
      size: 0,
      at: [603.4, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1001',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 590.54,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Approach — Door 1',
      size: 0,
      at: [594.8, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1002',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Approach — Door 2',
      size: 0,
      at: [480.3, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1003',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 590.54,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Approach — Door 3',
      size: 0,
      at: [594.8, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1004',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Approach — Door 4',
      size: 0,
      at: [480.3, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1005',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 590.54,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Approach — Door 5',
      size: 0,
      at: [594.8, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1006',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Approach — Door 6',
      size: 0,
      at: [480.3, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1007',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 590.54,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Approach — Door 7',
      size: 0,
      at: [594.8, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1008',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Approach — Door 8',
      size: 0,
      at: [480.3, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1009',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 590.54,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Approach — Door 9',
      size: 0,
      at: [594.8, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1010',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Approach — Door 10',
      size: 0,
      at: [480.3, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1011',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 590.54,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Approach — Door 11',
      size: 0,
      at: [594.8, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1012',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Approach — Door 12',
      size: 0,
      at: [480.3, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1013',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 590.54,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Approach — Door 13',
      size: 0,
      at: [594.8, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1014',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 476.0,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Approach — Door 14',
      size: 0,
      at: [480.3, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-1',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 533.27,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Back Passage 1',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-2',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 533.27,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Back Passage 2',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-3',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 533.27,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Back Passage 3',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-4',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 533.27,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Back Passage 4',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-5',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 533.27,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Back Passage 5',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-6',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 533.27,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Back Passage 6',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-7',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 533.27,
      y: 127.16,
      w: 8.59,
      h: 14.32,
      label: '',
      name: 'Back Passage 7',
      size: 0,
      at: [537.6, 134.3],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-c-port-corridor',
      tier: 'tier-1-c',
      region: null,
      x: 392.25,
      y: 95.38,
      w: 5.01,
      h: 8.59,
      label: '',
      name: 'Port Corridor',
      size: 0,
      at: [394.8, 99.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-warehouse',
      tier: 'tier-5',
      region: 't5-warehouses',
      x: 407.28,
      y: 473.64,
      w: 320.71,
      h: 34.36,
      label: 'Cha-R-Controlled Warehouse',
      name: 'Cha-R-Controlled Warehouse',
      size: 11,
      at: [567.6, 494.5],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-observation-deck',
      tier: 'tier-3',
      region: 't3-obs-deck',
      x: 647.81,
      y: 301.83,
      w: 172.2,
      h: 25.77,
      label: 'Observation Deck',
      name: 'Observation Deck',
      size: 11,
      at: [733.9, 318.4],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-residential-standard',
      tier: 'tier-3',
      region: 't3-residential-ord',
      x: 186.8,
      y: 310.42,
      w: 180.39,
      h: 17.18,
      label: 'Standard Residential Block',
      name: 'Standard Residential Block',
      size: 11,
      at: [277.0, 322.7],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-main-corridor',
      tier: 'tier-1',
      region: null,
      x: 256.95,
      y: 127.16,
      w: 210.46,
      h: 14.32,
      label: 'Main Corridor (port)',
      name: 'Main Corridor (port)',
      size: 8,
      at: [362.2, 137.0],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-standard-cabins',
      tier: 'tier-5',
      region: 't5-residential',
      x: 186.8,
      y: 495.11,
      w: 180.39,
      h: 12.89,
      label: 'Tier 5 Standard Cabins (forward)',
      name: 'Tier 5 Standard Cabins (forward)',
      size: 8,
      at: [277.0, 504.2],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-ei-i-family-office',
      tier: 'tier-4',
      region: 'tier-4-ei-i-family-office',
      x: 487.46,
      y: 404.92,
      w: 175.24,
      h: 12.88,
      label: 'Ei-I Family Office',
      name: 'Ei-I Family Office',
      size: 8,
      at: [575.1, 414.0],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-starboard-promenade',
      tier: 'tier-3',
      region: null,
      x: 820.01,
      y: 310.42,
      w: 128.46,
      h: 17.18,
      label: 'Starboard Promenade',
      name: 'Starboard Promenade',
      size: 11,
      at: [884.2, 322.7],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-xi-yu-family-office',
      tier: 'tier-4',
      region: 't4-xiyu',
      x: 327.11,
      y: 404.92,
      w: 160.35,
      h: 12.88,
      label: 'Xi-Yu Family Office',
      name: 'Xi-Yu Family Office',
      size: 8,
      at: [407.3, 414.0],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-princes-quarters-gate',
      tier: 'tier-1',
      region: null,
      x: 467.41,
      y: 127.16,
      w: 140.31,
      h: 14.32,
      label: "Princes' Quarters Gate",
      name: "Princes' Quarters Gate",
      size: 8,
      at: [537.6, 137.0],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-west-mid',
      tier: 'tier-4',
      region: null,
      x: 166.75,
      y: 404.92,
      w: 140.31,
      h: 12.88,
      label: 'West General Area (midships)',
      name: 'West General Area (midships)',
      size: 8,
      at: [236.9, 414.0],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-east',
      tier: 'tier-4',
      region: null,
      x: 677.88,
      y: 404.92,
      w: 140.3,
      h: 12.88,
      label: 'East General Area',
      name: 'East General Area',
      size: 8,
      at: [748.0, 414.0],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-detention-void',
      tier: 'tier-1',
      region: null,
      x: 738.01,
      y: 127.16,
      w: 120.26,
      h: 14.32,
      label: 'Starboard Forward Floor',
      name: 'Starboard Forward Floor',
      size: 8,
      at: [798.1, 137.0],
      cut: true,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-4-starboard-promenade',
      tier: 'tier-4',
      region: null,
      x: 818.18,
      y: 404.92,
      w: 130.29,
      h: 12.88,
      label: 'Starboard Promenade',
      name: 'Starboard Promenade',
      size: 8,
      at: [883.3, 414.0],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-port-promenade',
      tier: 'tier-1',
      region: null,
      x: 156.73,
      y: 127.16,
      w: 100.22,
      h: 14.32,
      label: 'Port Promenade',
      name: 'Port Promenade',
      size: 8,
      at: [206.8, 137.0],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-main-corridor-starboard',
      tier: 'tier-1',
      region: null,
      x: 607.72,
      y: 127.16,
      w: 100.22,
      h: 14.32,
      label: '',
      name: 'Main Corridor (starboard)',
      size: 0,
      at: [657.8, 134.3],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-port-promenade',
      tier: 'tier-2',
      region: null,
      x: 156.73,
      y: 218.79,
      w: 100.22,
      h: 14.32,
      label: 'Port Promenade',
      name: 'Port Promenade',
      size: 8,
      at: [206.8, 228.6],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-port-promenade',
      tier: 'tier-3',
      region: null,
      x: 106.62,
      y: 310.42,
      w: 80.18,
      h: 17.18,
      label: 'Port Promenade',
      name: 'Port Promenade',
      size: 8,
      at: [146.7, 321.7],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-starboard-promenade',
      tier: 'tier-2',
      region: null,
      x: 808.16,
      y: 218.79,
      w: 80.18,
      h: 14.32,
      label: '',
      name: 'Starboard Promenade',
      size: 0,
      at: [848.2, 225.9],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-port-promenade',
      tier: 'tier-5',
      region: null,
      x: 106.62,
      y: 495.11,
      w: 80.18,
      h: 12.89,
      label: 'Port Promenade',
      name: 'Port Promenade',
      size: 8,
      at: [146.7, 504.2],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-starboard-promenade',
      tier: 'tier-5',
      region: null,
      x: 727.99,
      y: 495.11,
      w: 80.17,
      h: 12.89,
      label: '',
      name: 'Starboard Promenade',
      size: 0,
      at: [768.1, 501.6],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-central-spine',
      tier: 'tier-3',
      region: null,
      x: 367.19,
      y: 310.42,
      w: 40.09,
      h: 17.18,
      label: '',
      name: 'Central Spine',
      size: 0,
      at: [387.2, 319.0],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-starboard-corridor',
      tier: 'tier-3',
      region: null,
      x: 607.72,
      y: 310.42,
      w: 40.09,
      h: 17.18,
      label: '',
      name: 'Starboard Corridor',
      size: 0,
      at: [627.8, 319.0],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-main-corridor',
      tier: 'tier-5',
      region: null,
      x: 367.19,
      y: 495.11,
      w: 40.09,
      h: 12.89,
      label: '',
      name: 'Main Corridor',
      size: 0,
      at: [387.2, 501.6],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-lifeboats-starboard',
      tier: 'tier-1',
      region: 'lifeboats',
      x: 858.27,
      y: 127.16,
      w: 30.07,
      h: 14.32,
      label: '',
      name: 'Lifeboat Deck (starboard)',
      size: 0,
      at: [873.3, 134.3],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-starboard-corridor',
      tier: 'tier-1',
      region: null,
      x: 707.94,
      y: 127.16,
      w: 30.07,
      h: 14.32,
      label: '',
      name: 'Starboard Corridor',
      size: 0,
      at: [723.0, 134.3],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-lifeboats-port',
      tier: 'tier-1',
      region: 'lifeboats',
      x: 126.67,
      y: 127.16,
      w: 30.06,
      h: 14.32,
      label: '',
      name: 'Lifeboat Deck (port)',
      size: 0,
      at: [141.7, 134.3],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-port-corridor',
      tier: 'tier-4',
      region: null,
      x: 136.69,
      y: 404.92,
      w: 30.06,
      h: 12.88,
      label: '',
      name: 'Port Corridor',
      size: 0,
      at: [151.7, 411.4],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-b-starboard-corridor',
      tier: 'tier-1-b',
      region: null,
      x: 707.94,
      y: 105.4,
      w: 30.07,
      h: 8.59,
      label: '',
      name: 'Starboard Corridor',
      size: 0,
      at: [723.0, 109.7],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-starboard-corridor',
      tier: 'tier-4',
      region: null,
      x: 662.84,
      y: 404.92,
      w: 15.04,
      h: 12.88,
      label: '',
      name: 'Starboard Corridor',
      size: 0,
      at: [670.4, 411.4],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-jail-block-walkway',
      tier: 'tier-1-b',
      region: null,
      x: 843.24,
      y: 105.4,
      w: 15.03,
      h: 8.59,
      label: '',
      name: 'Jail Block Walkway',
      size: 0,
      at: [850.8, 109.7],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-jail-block-hall',
      tier: 'tier-1-b',
      region: null,
      x: 738.01,
      y: 105.4,
      w: 15.03,
      h: 8.59,
      label: '',
      name: 'Jail Block Hall',
      size: 0,
      at: [745.5, 109.7],
      cut: true,
      through: true,
      inferred: true,
    },
  ]

  /**
   * A deck of the tier-1 liner is labelled to starboard and on one line: three
   * tiers-worth of tab on the port margin, three and a half metres apart, is
   * three labels written over each other.
   */
  const decks = [
    {
      id: 'tier-1-c',
      name: 'Tier 1 · Guest Deck',
      nameFr: 'Pont 1 · Pont des hôtes',
      child: true,
      x0: 333.55,
      x1: 746.6,
      floor: 103.97,
      ceiling: 95.38,
      elevation: 141.1,
    },
    {
      id: 'tier-1-b',
      name: 'Tier 1 · Garrison Deck',
      nameFr: 'Pont 1 · Pont de la garnison',
      child: true,
      x0: 604.14,
      x1: 858.27,
      floor: 113.99,
      ceiling: 105.4,
      elevation: 137.6,
    },
    {
      id: 'tier-1',
      name: 'Tier 1',
      nameFr: 'Pont 1',
      child: false,
      x0: 144.22,
      x1: 858.27,
      floor: 141.48,
      ceiling: 127.16,
      elevation: 128,
    },
    {
      id: 'tier-2',
      name: 'Tier 2',
      nameFr: 'Pont 2',
      child: false,
      x0: 94.11,
      x1: 908.38,
      floor: 233.11,
      ceiling: 218.79,
      elevation: 96,
    },
    {
      id: 'tier-3',
      name: 'Tier 3',
      nameFr: 'Pont 3',
      child: false,
      x0: 44.0,
      x1: 956.0,
      floor: 327.6,
      ceiling: 310.42,
      elevation: 63,
    },
    {
      id: 'tier-4',
      name: 'Tier 4',
      nameFr: 'Pont 4',
      child: false,
      x0: 51.5,
      x1: 948.47,
      floor: 417.8,
      ceiling: 404.92,
      elevation: 31.5,
    },
    {
      id: 'tier-5',
      name: 'Tier 5',
      nameFr: 'Pont 5',
      child: false,
      x0: 83.02,
      x1: 831.77,
      floor: 508.0,
      ceiling: 495.11,
      elevation: 0,
    },
  ]

  /**
   * A deck carries both of its names, because the tabs are the only labels on
   * the section that come from the ship's own data rather than the dictionary,
   * and a single name means one of the two languages reads the other's.
   */
  const deckName = (deck: { name: string; nameFr: string }) =>
    $locale === 'fr' ? deck.nameFr : deck.name

  const gaps = [
    {
      id: 'tier-5-tier-4',
      x: 83.02,
      y: 417.8,
      w: 748.75,
      h: 77.31,
      metres: 27.0,
    },
    {
      id: 'tier-4-tier-3',
      x: 51.5,
      y: 327.6,
      w: 896.97,
      h: 77.32,
      metres: 27.0,
    },
    {
      id: 'tier-3-tier-2',
      x: 94.11,
      y: 233.11,
      w: 814.27,
      h: 77.31,
      metres: 27,
    },
    {
      id: 'tier-2-tier-1',
      x: 144.22,
      y: 141.48,
      w: 714.05,
      h: 77.31,
      metres: 27,
    },
    {
      id: 'tier-1-tier-1-b',
      x: 604.14,
      y: 113.99,
      w: 254.13,
      h: 13.17,
      metres: 4.6,
    },
  ]

  /**
   * The liner over tier 1, open at the top edge of the drawing rather than
   * closed at a height. It is the only band here that says how far up the ship
   * goes by refusing to say it.
   */
  const superstructure = {
    x: 333.55,
    y: 0.0,
    w: 413.05,
    h: 95.38,
  }

  const waterline = 370.56

  /**
   * A room on the section opens the deck it belongs to and then itself, which
   * is the same two steps a reader takes by hand: the section is the way in to
   * a deck, not a replacement for it.
   */
  function open(room: Room) {
    mapState.selectTier(room.tier)
    if (room.region) mapState.selectLocation(room.region)
  }

  function openWithKeyboard(event: KeyboardEvent, room: Room) {
    if (event.key !== 'Enter' && event.key !== ' ') return
    event.preventDefault()
    event.stopPropagation()
    open(room)
  }

  function openDeck(tierId: string) {
    mapState.selectTier(tierId)
  }

  function openDeckWithKeyboard(event: KeyboardEvent, tierId: string) {
    if (event.key !== 'Enter' && event.key !== ' ') return
    event.preventDefault()
    openDeck(tierId)
  }
</script>

<svg viewBox="0 0 1000 600" class="w-full h-full text-[#FFFFF0]">
  <defs>
    <style>
      .sea {
        fill: #0f172a;
      }
      .hull {
        fill: #1a0f0f;
        stroke: #ffd700;
        stroke-width: 3;
      }
      .room {
        fill: #2a1515;
        stroke: #fffff0;
        stroke-width: 1;
        transition: fill 0.2s;
      }
      .room.behind {
        fill: #221010;
        stroke: #fffff0;
        stroke-opacity: 0.18;
        stroke-width: 0.5;
        fill-opacity: 0.55;
      }
      .room.clickable {
        cursor: pointer;
      }
      .room.clickable:hover {
        fill: #3d1c1c;
      }
      g[role='button']:focus .room {
        stroke: #ffd700;
        stroke-width: 2;
      }
      .room.through {
        fill: #150b0b;
        stroke: #ffd700;
        stroke-opacity: 0.35;
        stroke-dasharray: 4 4;
      }
      .room.inferred {
        fill: #16171c;
        stroke: #9dc4e0;
        stroke-opacity: 0.4;
      }
      .gap {
        fill: url(#unbuilt);
        stroke: #ffd700;
        stroke-opacity: 0.12;
        stroke-width: 0.5;
      }
      .deck-rule {
        stroke: #ffd700;
        stroke-opacity: 0.45;
        stroke-width: 1;
        stroke-dasharray: 2 5;
      }
      .deck-tab {
        cursor: pointer;
      }
      .deck-tab text {
        fill: #ffd700;
        font-family: sans-serif;
        font-size: 12px;
        letter-spacing: 1px;
      }
      .deck-tab:hover text {
        fill: #fffff0;
      }
      .label {
        fill: #fffff0;
        font-family: sans-serif;
        pointer-events: none;
        text-anchor: middle;
      }
      .note {
        fill: #fffff0;
        fill-opacity: 0.5;
        font-family: sans-serif;
        font-size: 10px;
        pointer-events: none;
      }
      .waterline {
        stroke: #9dc4e0;
        stroke-opacity: 0.55;
        stroke-width: 1.5;
        stroke-dasharray: 8 6;
      }
    </style>
    <!-- The liner fades out toward the top edge rather than stopping at a line:
         the drawing does not know how tall it is, and says so. -->
    <linearGradient id="open-top" x1="0" y1="1" x2="0" y2="0">
      <stop offset="0" stop-color="#fff" stop-opacity="1" />
      <stop offset="1" stop-color="#fff" stop-opacity="0" />
    </linearGradient>
    <mask id="fade-up">
      <rect x="333.55" y="0.0" width="413.05" height="95.38" fill="url(#open-top)" />
    </mask>
    <pattern
      id="unbuilt"
      width="6"
      height="6"
      patternTransform="rotate(45)"
      patternUnits="userSpaceOnUse"
    >
      <rect width="6" height="6" fill="#140d0d" />
      <line x1="0" y1="0" x2="0" y2="6" stroke="#ffd700" stroke-opacity="0.13" stroke-width="1.5" />
    </pattern>
  </defs>

  <rect class="sea" x="0" y={waterline} width="1000" height={600 - waterline} />

  <polygon
    class="hull"
    points="83.02,508.0 83.02,495.11 51.5,417.8 51.5,404.92 44.0,327.6 44.0,310.42 94.11,233.11 94.11,218.79 144.22,141.48 144.22,127.16 604.14,113.99 604.14,105.4 333.55,103.97 333.55,95.38 746.6,95.38 746.6,103.97 858.27,105.4 858.27,113.99 858.27,127.16 858.27,141.48 908.38,218.79 908.38,233.11 956.0,310.42 956.0,327.6 948.47,404.92 948.47,417.8 831.77,495.11 831.77,508.0"
  />

  <rect
    class="gap"
    mask="url(#fade-up)"
    x={superstructure.x}
    y={superstructure.y}
    width={superstructure.w}
    height={superstructure.h}
  />

  {#each gaps as gap (gap.id)}
    <rect class="gap" x={gap.x} y={gap.y} width={gap.w} height={gap.h} />
  {/each}

  <g id="section-rooms">
    {#each rooms as room (room.id)}
      {#if room.cut && room.region}
        <g
          role="button"
          tabindex="0"
          aria-label={room.name}
          onclick={() => open(room)}
          onkeydown={(event) => openWithKeyboard(event, room)}
        >
          <title>{room.name}</title>
          <rect
            class="room clickable"
            class:through={room.through}
            class:inferred={room.inferred}
            x={room.x}
            y={room.y}
            width={room.w}
            height={room.h}
          />
        </g>
      {:else}
        <rect
          class="room"
          class:behind={!room.cut}
          class:through={room.through}
          class:inferred={room.inferred}
          x={room.x}
          y={room.y}
          width={room.w}
          height={room.h}
        />
      {/if}
    {/each}

    {#each rooms.filter((room) => room.size > 0) as room (room.id)}
      <text class="label" x={room.at[0]} y={room.at[1]} font-size={room.size}>{room.label}</text>
    {/each}
  </g>

  <line class="waterline" x1="0" y1={waterline} x2="1000" y2={waterline} />

  <!-- The eye of the ch. 349 page: low, forward, and opening nothing. -->
  <circle
    cx="135.26"
    cy="350.51"
    r="14.3"
    fill="#050505"
    stroke="#ffd700"
    stroke-width="2"
    pointer-events="none"
  />
  <circle cx="135.26" cy="350.51" r="5.5" fill="#fffff0" pointer-events="none" />

  {#each decks as deck (deck.id)}
    <line class="deck-rule" x1={deck.x0} y1={deck.floor} x2={deck.x1} y2={deck.floor} />
    <g
      class="deck-tab"
      role="button"
      tabindex="0"
      aria-label={deckName(deck)}
      onclick={() => openDeck(deck.id)}
      onkeydown={(event) => openDeckWithKeyboard(event, deck.id)}
    >
      {#if deck.child}
        <text x="1000" y={deck.ceiling + 11} text-anchor="end" font-size="10"
          >{deckName(deck)} · {deck.elevation} m</text
        >
      {:else}
        <text x="6" y={deck.ceiling + 12}>{deckName(deck)}</text>
        <text x="6" y={deck.ceiling + 25} font-size="9" fill-opacity="0.55">{deck.elevation} m</text
        >
      {/if}
    </g>
  {/each}

  {#each gaps as gap (gap.id)}
    {#if gap.h > 26}
      <text class="note" x={gap.x + gap.w / 2} y={gap.y + gap.h / 2 + 3} text-anchor="middle"
        >{$t.ship.unmodelledDecks(gap.metres)}</text
      >
    {/if}
  {/each}

  <text
    class="note"
    x={superstructure.x + superstructure.w / 2}
    y={superstructure.y + superstructure.h - 12}
    text-anchor="middle">{$t.ship.superstructure}</text
  >
</svg>
