<script lang="ts">
  /**
   * The Black Whale in longitudinal section, generated from
   * `data/ship/blueprint.json` by `scripts/generate-section-map.py`.
   *
   * Cut on the centreline, looking to starboard, bow to the left — the view of
   * the ch. 349 double page, drawn from the reconstruction instead of traced.
   * One unit is 0.203 m; the section has its own scale because 175 m of ship
   * and 77 m of freeboard do not fit the deck plans' 0.35 m per unit.
   *
   * Rooms the cut passes through are solid, labelled where the label fits, and
   * open their deck. Rooms it passes beside — everything to port or starboard —
   * are drawn behind and dim: they are what fills the ship, and on the manga
   * page they are the strips of texture between the labelled callouts.
   *
   * The banded gaps are the decks this reconstruction does not hold. The ship
   * has 41 of them and the tour walks 5, so about thirteen metres of ship sit
   * between each pair. Nothing is drawn inside them, because nothing is known
   * to be.
   *
   * The band over tier 1 is the same admission, and it is open at the top: the
   * ch. 369 exterior shows a liner terraced a dozen levels above the one floor
   * of it anyone has drawn a plan for. Closing that band at a height would be a
   * claim about how tall the liner is, and the page gives its shape, not its
   * scale.
   *
   * Do not hand-edit — regenerate from the blueprint.
   */
  import { mapState } from '$lib/state/mapState.svelte'
  import { t } from '$lib/i18n'

  type Room = {
    id: string
    tier: string
    region: string | null
    x: number
    y: number
    w: number
    h: number
    label: string
    name: string
    size: number
    at: [number, number]
    cut: boolean
    through: boolean
    inferred: boolean
  }

  const rooms: Room[] = [
    {
      id: 'tier-3-central-spine',
      tier: 'tier-3',
      region: null,
      x: 130.21,
      y: 301.1,
      w: 637.94,
      h: 29.56,
      label: '',
      name: 'Central Spine',
      size: 0,
      at: [449.2, 315.9],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-starboard-corridor',
      tier: 'tier-3',
      region: null,
      x: 130.21,
      y: 301.1,
      w: 637.94,
      h: 29.56,
      label: '',
      name: 'Starboard Corridor',
      size: 0,
      at: [449.2, 315.9],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-port-promenade',
      tier: 'tier-3',
      region: null,
      x: 130.21,
      y: 301.1,
      w: 637.94,
      h: 29.56,
      label: '',
      name: 'Port Promenade',
      size: 0,
      at: [449.2, 315.9],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-starboard-promenade',
      tier: 'tier-3',
      region: null,
      x: 130.21,
      y: 301.1,
      w: 637.94,
      h: 29.56,
      label: '',
      name: 'Starboard Promenade',
      size: 0,
      at: [449.2, 315.9],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-port-corridor',
      tier: 'tier-4',
      region: null,
      x: 95.73,
      y: 397.16,
      w: 724.15,
      h: 22.17,
      label: '',
      name: 'Port Corridor',
      size: 0,
      at: [457.8, 408.2],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-general-area-east',
      tier: 'tier-4',
      region: null,
      x: 95.73,
      y: 397.16,
      w: 689.67,
      h: 22.17,
      label: '',
      name: 'East General Area',
      size: 0,
      at: [440.6, 408.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-starboard-corridor',
      tier: 'tier-4',
      region: null,
      x: 95.73,
      y: 397.16,
      w: 689.67,
      h: 22.17,
      label: '',
      name: 'Starboard Corridor',
      size: 0,
      at: [440.6, 408.2],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-starboard-promenade',
      tier: 'tier-4',
      region: null,
      x: 95.73,
      y: 397.16,
      w: 689.67,
      h: 22.17,
      label: '',
      name: 'Starboard Promenade',
      size: 0,
      at: [440.6, 408.2],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-port-promenade',
      tier: 'tier-1',
      region: null,
      x: 164.69,
      y: 128.68,
      w: 603.46,
      h: 24.63,
      label: '',
      name: 'Port Promenade',
      size: 0,
      at: [466.4, 141.0],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-port-promenade',
      tier: 'tier-2',
      region: null,
      x: 185.38,
      y: 217.35,
      w: 600.02,
      h: 24.63,
      label: '',
      name: 'Port Promenade',
      size: 0,
      at: [485.4, 229.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-starboard-promenade',
      tier: 'tier-2',
      region: null,
      x: 185.38,
      y: 217.35,
      w: 600.02,
      h: 24.63,
      label: '',
      name: 'Starboard Promenade',
      size: 0,
      at: [485.4, 229.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-central-courthouse',
      tier: 'tier-3',
      region: 'central-courthouse',
      x: 475.04,
      y: 291.25,
      w: 293.11,
      h: 39.41,
      label: '',
      name: 'Central Courthouse',
      size: 0,
      at: [621.6, 311.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-starboard-corridor',
      tier: 'tier-1',
      region: null,
      x: 302.63,
      y: 128.68,
      w: 465.52,
      h: 24.63,
      label: '',
      name: 'Starboard Corridor',
      size: 0,
      at: [535.4, 141.0],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-screening-room',
      tier: 'tier-2',
      region: 't2-screening-room',
      x: 509.53,
      y: 192.72,
      w: 224.14,
      h: 49.26,
      label: '',
      name: 'Screening Room',
      size: 0,
      at: [621.6, 217.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-port-promenade',
      tier: 'tier-5',
      region: null,
      x: 216.42,
      y: 485.83,
      w: 465.53,
      h: 22.17,
      label: '',
      name: 'Port Promenade',
      size: 0,
      at: [449.2, 496.9],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-starboard-promenade',
      tier: 'tier-5',
      region: null,
      x: 216.42,
      y: 485.83,
      w: 465.53,
      h: 22.17,
      label: '',
      name: 'Starboard Promenade',
      size: 0,
      at: [449.2, 496.9],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-residential-standard',
      tier: 'tier-3',
      region: 't3-residential-ord',
      x: 423.32,
      y: 301.1,
      w: 344.83,
      h: 29.56,
      label: '',
      name: 'Standard Residential Block',
      size: 0,
      at: [595.7, 315.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vip-casino',
      tier: 'tier-1-c',
      region: 'casino',
      x: 492.29,
      y: 49.37,
      w: 258.62,
      h: 39.41,
      label: '',
      name: 'VIP Casino',
      size: 0,
      at: [621.6, 69.1],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-main-corridor',
      tier: 'tier-5',
      region: null,
      x: 250.9,
      y: 485.83,
      w: 431.05,
      h: 22.17,
      label: '',
      name: 'Main Corridor',
      size: 0,
      at: [466.4, 496.9],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-observation-deck',
      tier: 'tier-3',
      region: 't3-obs-deck',
      x: 371.59,
      y: 286.32,
      w: 189.66,
      h: 44.34,
      label: '',
      name: 'Observation Deck',
      size: 0,
      at: [466.4, 308.5],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-cineplex',
      tier: 'tier-3',
      region: 't3-cinema',
      x: 130.21,
      y: 291.25,
      w: 206.9,
      h: 39.41,
      label: '',
      name: 'Cineplex',
      size: 0,
      at: [233.7, 311.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-residential-first-class',
      tier: 'tier-3',
      region: 't3-residential-1st',
      x: 130.21,
      y: 301.1,
      w: 258.63,
      h: 29.56,
      label: '',
      name: 'First-Class Residential Block',
      size: 0,
      at: [259.5, 315.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-central-dining-hall',
      tier: 'tier-5',
      region: 'central-dining-hall',
      x: 526.77,
      y: 463.66,
      w: 155.18,
      h: 44.34,
      label: '',
      name: 'Central Dining Hall',
      size: 0,
      at: [604.4, 485.8],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-central-police-station',
      tier: 'tier-3',
      region: 'central-police-station',
      x: 475.04,
      y: 301.1,
      w: 224.15,
      h: 29.56,
      label: '',
      name: 'Central Police Station',
      size: 0,
      at: [587.1, 315.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-b-starboard-corridor',
      tier: 'tier-1-b',
      region: null,
      x: 337.11,
      y: 91.24,
      w: 443.36,
      h: 14.78,
      label: '',
      name: 'Starboard Corridor',
      size: 0,
      at: [558.8, 98.6],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-vvip-corridor',
      tier: 'tier-1',
      region: 'vvip-living-quarters',
      x: 492.29,
      y: 128.68,
      w: 258.62,
      h: 24.63,
      label: '',
      name: 'VVIP Block Corridor',
      size: 0,
      at: [621.6, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-garrison-void',
      tier: 'tier-1',
      region: null,
      x: 492.29,
      y: 128.68,
      w: 258.62,
      h: 24.63,
      label: '',
      name: 'Starboard Quarters Floor',
      size: 0,
      at: [621.6, 141.0],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-1-casino-void',
      tier: 'tier-1',
      region: null,
      x: 492.29,
      y: 128.68,
      w: 258.62,
      h: 24.63,
      label: '',
      name: 'Port Inner Floor',
      size: 0,
      at: [621.6, 141.0],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-1-queens-void',
      tier: 'tier-1',
      region: null,
      x: 492.29,
      y: 128.68,
      w: 258.62,
      h: 24.63,
      label: '',
      name: 'Port Central Floor',
      size: 0,
      at: [621.6, 141.0],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-2-vip-quarters',
      tier: 'tier-2',
      region: null,
      x: 216.42,
      y: 217.35,
      w: 258.62,
      h: 24.63,
      label: '',
      name: 'VIP Quarters',
      size: 0,
      at: [345.7, 229.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-standard-cabins',
      tier: 'tier-5',
      region: 't5-residential',
      x: 250.9,
      y: 485.83,
      w: 284.49,
      h: 22.17,
      label: '',
      name: 'Tier 5 Standard Cabins (forward)',
      size: 0,
      at: [393.1, 496.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-corridor-port',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 492.29,
      y: 128.68,
      w: 241.38,
      h: 24.63,
      label: '',
      name: "Guards' Round (port)",
      size: 0,
      at: [613.0, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-corridor-starboard',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 492.29,
      y: 128.68,
      w: 241.38,
      h: 24.63,
      label: '',
      name: "Guards' Round (starboard)",
      size: 0,
      at: [613.0, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-west-north',
      tier: 'tier-4',
      region: null,
      x: 95.73,
      y: 397.16,
      w: 258.62,
      h: 22.17,
      label: '',
      name: 'West General Area (forward)',
      size: 0,
      at: [225.0, 408.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-center-north',
      tier: 'tier-4',
      region: null,
      x: 95.73,
      y: 397.16,
      w: 258.62,
      h: 22.17,
      label: '',
      name: 'Central General Area (forward)',
      size: 0,
      at: [225.0, 408.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-royal-army-conference-room',
      tier: 'tier-4',
      region: 'royal-army-office',
      x: 95.73,
      y: 397.16,
      w: 258.62,
      h: 22.17,
      label: '',
      name: 'Kakin Royal Army Conference Room',
      size: 0,
      at: [225.0, 408.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-banquet-hall-service-end',
      tier: 'tier-1',
      region: 'banquet-hall',
      x: 337.11,
      y: 108.98,
      w: 120.69,
      h: 47.29,
      label: '',
      name: 'Banquet Hall (service end)',
      size: 0,
      at: [397.5, 132.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-detention-void',
      tier: 'tier-1',
      region: null,
      x: 337.11,
      y: 128.68,
      w: 224.14,
      h: 24.63,
      label: '',
      name: 'Starboard Forward Floor',
      size: 0,
      at: [449.2, 141.0],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-2-ministry-of-justice',
      tier: 'tier-2',
      region: 't2-justice',
      x: 509.53,
      y: 217.35,
      w: 224.14,
      h: 24.63,
      label: '',
      name: 'Ministry of Justice',
      size: 0,
      at: [621.6, 229.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-2-vip-witness-protection-area',
      tier: 'tier-2',
      region: 't2-justice',
      x: 509.53,
      y: 217.35,
      w: 224.14,
      h: 24.63,
      label: '',
      name: 'VIP Witness Protection Area',
      size: 0,
      at: [621.6, 229.7],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-supreme-court',
      tier: 'tier-1-b',
      region: 'supreme-court',
      x: 595.74,
      y: 66.61,
      w: 137.93,
      h: 39.41,
      label: '',
      name: 'Supreme Court',
      size: 0,
      at: [664.7, 86.3],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-heilly-family-office',
      tier: 'tier-3',
      region: 't3-heilly',
      x: 595.74,
      y: 301.1,
      w: 172.41,
      h: 29.56,
      label: '',
      name: 'Heil-Ly Family Office',
      size: 0,
      at: [681.9, 315.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-lifeboats-port',
      tier: 'tier-1',
      region: 'lifeboats',
      x: 388.84,
      y: 128.68,
      w: 172.41,
      h: 24.63,
      label: '',
      name: 'Lifeboat Deck (port)',
      size: 0,
      at: [475.0, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-lifeboats-starboard',
      tier: 'tier-1',
      region: 'lifeboats',
      x: 388.84,
      y: 128.68,
      w: 172.41,
      h: 24.63,
      label: '',
      name: 'Lifeboat Deck (starboard)',
      size: 0,
      at: [475.0, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-west-south',
      tier: 'tier-4',
      region: null,
      x: 595.74,
      y: 397.16,
      w: 189.66,
      h: 22.17,
      label: '',
      name: 'West General Area (aft)',
      size: 0,
      at: [690.6, 408.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-general-area-center-south',
      tier: 'tier-4',
      region: null,
      x: 595.74,
      y: 397.16,
      w: 189.66,
      h: 22.17,
      label: '',
      name: 'Central General Area (aft)',
      size: 0,
      at: [690.6, 408.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-medical-clinic',
      tier: 'tier-4',
      region: null,
      x: 595.74,
      y: 397.16,
      w: 189.66,
      h: 22.17,
      label: '',
      name: 'Tier 4 Medical Clinic',
      size: 0,
      at: [690.6, 408.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-soldiers-living-quarters',
      tier: 'tier-1-b',
      region: 'soldiers-living-quarters',
      x: 492.29,
      y: 91.24,
      w: 258.62,
      h: 14.78,
      label: '',
      name: "Soldiers' Living Quarters",
      size: 0,
      at: [621.6, 98.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-corridor',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 492.29,
      y: 74.0,
      w: 258.62,
      h: 14.78,
      label: '',
      name: "Queens' Quarters Corridor",
      size: 0,
      at: [621.6, 81.4],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-c-port-corridor',
      tier: 'tier-1-c',
      region: null,
      x: 492.29,
      y: 74.0,
      w: 258.62,
      h: 14.78,
      label: '',
      name: 'Port Corridor',
      size: 0,
      at: [621.6, 81.4],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-medical-clinic',
      tier: 'tier-5',
      region: 't5-medical-none',
      x: 526.77,
      y: 485.83,
      w: 155.18,
      h: 22.17,
      label: '',
      name: 'Tier 5 Medical Clinic',
      size: 0,
      at: [604.4, 496.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-service-corridor-forward',
      tier: 'tier-5',
      region: null,
      x: 526.77,
      y: 485.83,
      w: 155.18,
      h: 22.17,
      label: '',
      name: 'Passage to the Great Refectory',
      size: 0,
      at: [604.4, 496.9],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-5-service-corridor-aft',
      tier: 'tier-5',
      region: null,
      x: 526.77,
      y: 485.83,
      w: 155.18,
      h: 22.17,
      label: '',
      name: 'Service Corridor (aft)',
      size: 0,
      at: [604.4, 496.9],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-court-void',
      tier: 'tier-1',
      region: null,
      x: 595.74,
      y: 128.68,
      w: 137.93,
      h: 24.63,
      label: '',
      name: 'Starboard Aft Floor',
      size: 0,
      at: [664.7, 141.0],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-1-jail-block-hall',
      tier: 'tier-1-b',
      region: null,
      x: 337.11,
      y: 91.24,
      w: 224.14,
      h: 14.78,
      label: '',
      name: 'Jail Block Hall',
      size: 0,
      at: [449.2, 98.6],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-jail-block-walkway',
      tier: 'tier-1-b',
      region: null,
      x: 388.84,
      y: 91.24,
      w: 172.41,
      h: 14.78,
      label: '',
      name: 'Jail Block Walkway',
      size: 0,
      at: [475.0, 98.6],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-general-area-west-mid',
      tier: 'tier-4',
      region: null,
      x: 423.32,
      y: 397.16,
      w: 103.45,
      h: 22.17,
      label: '',
      name: 'West General Area (midships)',
      size: 0,
      at: [475.0, 408.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-xi-yu-family-office',
      tier: 'tier-4',
      region: 't4-xiyu',
      x: 423.32,
      y: 397.16,
      w: 103.45,
      h: 22.17,
      label: '',
      name: 'Xi-Yu Family Office',
      size: 0,
      at: [475.0, 408.2],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-princes-burial-chamber',
      tier: 'tier-1',
      region: 'princes-burial-chamber',
      x: 63.16,
      y: 123.75,
      w: 75.67,
      h: 29.56,
      label: '',
      name: "Princes' Burial Chamber",
      size: 0,
      at: [101.0, 138.5],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-residential-units',
      tier: 'tier-3',
      region: 'central-police-station',
      x: 699.19,
      y: 301.1,
      w: 68.96,
      h: 29.56,
      label: '',
      name: 'Central Police Dorm Room',
      size: 0,
      at: [733.7, 315.9],
      cut: false,
      through: false,
      inferred: true,
    },
    {
      id: 'tier-5-standard-cabins-aft',
      tier: 'tier-5',
      region: 't5-residential',
      x: 604.36,
      y: 485.83,
      w: 77.59,
      h: 22.17,
      label: '',
      name: 'Tier 5 Standard Cabins (aft)',
      size: 0,
      at: [643.2, 496.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-2-tier-1-access',
      tier: 'tier-2',
      region: null,
      x: 116.42,
      y: 217.35,
      w: 68.96,
      h: 24.63,
      label: '',
      name: 'Tier 1 Stairwell',
      size: 0,
      at: [150.9, 229.7],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-vvip-restricted-royal-02',
      tier: 'tier-1',
      region: null,
      x: 556.94,
      y: 128.68,
      w: 64.66,
      h: 24.63,
      label: '',
      name: 'Restricted Royal Suite 2',
      size: 0,
      at: [589.3, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-suite-01',
      tier: 'tier-1',
      region: null,
      x: 621.6,
      y: 128.68,
      w: 64.66,
      h: 24.63,
      label: '',
      name: 'VVIP Suite 1',
      size: 0,
      at: [653.9, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-suite-04',
      tier: 'tier-1',
      region: null,
      x: 556.94,
      y: 128.68,
      w: 64.66,
      h: 24.63,
      label: '',
      name: 'VVIP Suite 4',
      size: 0,
      at: [589.3, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-mafia-suite',
      tier: 'tier-1',
      region: null,
      x: 621.6,
      y: 128.68,
      w: 64.66,
      h: 24.63,
      label: '',
      name: 'Mafia VVIP Suite',
      size: 0,
      at: [653.9, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-restricted-royal-01',
      tier: 'tier-1',
      region: null,
      x: 492.29,
      y: 128.68,
      w: 64.65,
      h: 24.63,
      label: '',
      name: 'Restricted Royal Suite 1',
      size: 0,
      at: [524.6, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-suite-02',
      tier: 'tier-1',
      region: null,
      x: 686.26,
      y: 128.68,
      w: 64.65,
      h: 24.63,
      label: '',
      name: 'VVIP Suite 2',
      size: 0,
      at: [718.6, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-suite-03',
      tier: 'tier-1',
      region: null,
      x: 492.29,
      y: 128.68,
      w: 64.65,
      h: 24.63,
      label: '',
      name: 'VVIP Suite 3',
      size: 0,
      at: [524.6, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-v5-suite',
      tier: 'tier-1',
      region: null,
      x: 686.26,
      y: 128.68,
      w: 64.65,
      h: 24.63,
      label: '',
      name: "V5 Politician's Suite",
      size: 0,
      at: [718.6, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-residential-room-3101',
      tier: 'tier-3',
      region: 'room-3101',
      x: 268.14,
      y: 301.1,
      w: 51.73,
      h: 29.56,
      label: '',
      name: 'Room 3101 (Heil-Ly Trap)',
      size: 0,
      at: [294.0, 315.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-area-37564',
      tier: 'tier-5',
      region: 'room-37564',
      x: 535.39,
      y: 485.83,
      w: 68.97,
      h: 22.17,
      label: '',
      name: 'Area 37564',
      size: 0,
      at: [569.9, 496.9],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-cabin-cross-corridor-west',
      tier: 'tier-5',
      region: null,
      x: 535.39,
      y: 485.83,
      w: 68.97,
      h: 22.17,
      label: '',
      name: 'Cabin Cross Corridor (west)',
      size: 0,
      at: [569.9, 496.9],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-cabin-cross-corridor-east',
      tier: 'tier-5',
      region: null,
      x: 535.39,
      y: 485.83,
      w: 68.97,
      h: 22.17,
      label: '',
      name: 'Cabin Cross Corridor (east)',
      size: 0,
      at: [569.9, 496.9],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-vip-jail',
      tier: 'tier-1-b',
      region: 'vip-detention',
      x: 475.04,
      y: 91.24,
      w: 68.97,
      h: 14.78,
      label: '',
      name: 'VIP Jail',
      size: 0,
      at: [509.5, 98.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-vvip-prison-beyond',
      tier: 'tier-1-b',
      region: 'beyond-cell',
      x: 388.84,
      y: 91.24,
      w: 68.96,
      h: 14.78,
      label: '',
      name: "Beyond Netero's Holding Cell",
      size: 0,
      at: [423.3, 98.6],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-01',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 492.29,
      y: 74.0,
      w: 64.68,
      h: 14.78,
      label: '',
      name: "Queen's Room 01",
      size: 0,
      at: [524.6, 81.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-02',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 492.29,
      y: 74.0,
      w: 64.68,
      h: 14.78,
      label: '',
      name: "Queen's Room 02",
      size: 0,
      at: [524.6, 81.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-05',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 621.6,
      y: 74.0,
      w: 64.68,
      h: 14.78,
      label: '',
      name: "Queen's Room 05",
      size: 0,
      at: [653.9, 81.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-06',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 621.6,
      y: 74.0,
      w: 64.68,
      h: 14.78,
      label: '',
      name: "Queen's Room 06",
      size: 0,
      at: [653.9, 81.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-03',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 556.97,
      y: 74.0,
      w: 64.63,
      h: 14.78,
      label: '',
      name: "Queen's Room 03",
      size: 0,
      at: [589.3, 81.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-04',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 556.97,
      y: 74.0,
      w: 64.63,
      h: 14.78,
      label: '',
      name: "Queen's Room 04",
      size: 0,
      at: [589.3, 81.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-07',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 686.28,
      y: 74.0,
      w: 64.63,
      h: 14.78,
      label: '',
      name: "Queen's Room 07",
      size: 0,
      at: [718.6, 81.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-queens-living-quarters-room-08',
      tier: 'tier-1-c',
      region: 'queens-living-quarters',
      x: 686.28,
      y: 74.0,
      w: 64.63,
      h: 14.78,
      label: '',
      name: "Queen's Room 08",
      size: 0,
      at: [718.6, 81.4],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-main-corridor',
      tier: 'tier-1',
      region: null,
      x: 457.8,
      y: 128.68,
      w: 34.49,
      h: 24.63,
      label: '',
      name: 'Main Corridor (port)',
      size: 0,
      at: [475.0, 141.0],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-main-corridor-starboard',
      tier: 'tier-1',
      region: null,
      x: 457.8,
      y: 128.68,
      w: 34.49,
      h: 24.63,
      label: '',
      name: 'Main Corridor (starboard)',
      size: 0,
      at: [475.0, 141.0],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-burial-passage',
      tier: 'tier-1',
      region: null,
      x: 138.83,
      y: 128.68,
      w: 25.86,
      h: 24.63,
      label: '',
      name: 'Burial Chamber Passage',
      size: 0,
      at: [151.8, 141.0],
      cut: false,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1009',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1009',
      x: 633.91,
      y: 128.68,
      w: 24.64,
      h: 24.63,
      label: '',
      name: 'Room 1009 (Halkenburg)',
      size: 0,
      at: [646.2, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1009',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 633.91,
      y: 128.68,
      w: 24.64,
      h: 24.63,
      label: '',
      name: 'Approach — Door 9',
      size: 0,
      at: [646.2, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1010',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 633.91,
      y: 128.68,
      w: 24.64,
      h: 24.63,
      label: '',
      name: 'Approach — Door 10',
      size: 0,
      at: [646.2, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-5',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 633.91,
      y: 128.68,
      w: 24.64,
      h: 24.63,
      label: '',
      name: 'Back Passage 5',
      size: 0,
      at: [646.2, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1001',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1001',
      x: 500.91,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Room 1001 (Benjamin)',
      size: 0,
      at: [513.2, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1003',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1003',
      x: 534.16,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Room 1003 (Zhang Lei)',
      size: 0,
      at: [546.5, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1005',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1005',
      x: 567.41,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Room 1005 (Tubeppa)',
      size: 0,
      at: [579.7, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1007',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1007',
      x: 600.66,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Room 1007 (Luzurus)',
      size: 0,
      at: [613.0, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1011',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1011',
      x: 667.17,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Room 1011 (Fugetsu)',
      size: 0,
      at: [679.5, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1013',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1013',
      x: 700.42,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Room 1013 (Marayam)',
      size: 0,
      at: [712.7, 141.0],
      cut: false,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1001',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 500.91,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Approach — Door 1',
      size: 0,
      at: [513.2, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1002',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 500.91,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Approach — Door 2',
      size: 0,
      at: [513.2, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1003',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 534.16,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Approach — Door 3',
      size: 0,
      at: [546.5, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1004',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 534.16,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Approach — Door 4',
      size: 0,
      at: [546.5, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1005',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 567.41,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Approach — Door 5',
      size: 0,
      at: [579.7, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1006',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 567.41,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Approach — Door 6',
      size: 0,
      at: [579.7, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1007',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 600.66,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Approach — Door 7',
      size: 0,
      at: [613.0, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1008',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 600.66,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Approach — Door 8',
      size: 0,
      at: [613.0, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1011',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 667.17,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Approach — Door 11',
      size: 0,
      at: [679.5, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1012',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 667.17,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Approach — Door 12',
      size: 0,
      at: [679.5, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1013',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 700.42,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Approach — Door 13',
      size: 0,
      at: [712.7, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-approach-1014',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 700.42,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Approach — Door 14',
      size: 0,
      at: [712.7, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-1',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 500.91,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Back Passage 1',
      size: 0,
      at: [513.2, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-2',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 534.16,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Back Passage 2',
      size: 0,
      at: [546.5, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-3',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 567.41,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Back Passage 3',
      size: 0,
      at: [579.7, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-4',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 600.66,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Back Passage 4',
      size: 0,
      at: [613.0, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-6',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 667.17,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Back Passage 6',
      size: 0,
      at: [679.5, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-back-passage-7',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 700.42,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Back Passage 7',
      size: 0,
      at: [712.7, 141.0],
      cut: false,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-5-warehouse',
      tier: 'tier-5',
      region: 't5-warehouses',
      x: 250.9,
      y: 448.89,
      w: 241.39,
      h: 59.11,
      label: 'Cha-R-Controlled Warehouse',
      name: 'Cha-R-Controlled Warehouse',
      size: 11,
      at: [371.6, 482.1],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-central-hospital',
      tier: 'tier-3',
      region: 't3-hospital',
      x: 130.21,
      y: 301.1,
      w: 310.35,
      h: 29.56,
      label: 'Central Hospital',
      name: 'Central Hospital',
      size: 11,
      at: [285.4, 319.5],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-2-heilly-secret-hideout',
      tier: 'tier-2',
      region: 't2-vip',
      x: 216.42,
      y: 217.35,
      w: 258.62,
      h: 24.63,
      label: 'Heil-Ly Secret Hideout',
      name: 'Heil-Ly Secret Hideout',
      size: 11,
      at: [345.7, 233.3],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-banquet-hall',
      tier: 'tier-1',
      region: 'banquet-hall',
      x: 337.11,
      y: 108.98,
      w: 120.69,
      h: 44.33,
      label: 'Banquet Hall',
      name: 'Banquet Hall',
      size: 11,
      at: [397.5, 134.8],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-king-living-quarters',
      tier: 'tier-1',
      region: 'king-quarters',
      x: 164.69,
      y: 118.83,
      w: 137.94,
      h: 34.48,
      label: "King's Living Quarters",
      name: "King's Living Quarters",
      size: 11,
      at: [233.7, 139.7],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-cha-r-family-office',
      tier: 'tier-5',
      region: 't5-char',
      x: 526.77,
      y: 485.83,
      w: 155.18,
      h: 22.17,
      label: 'Cha-R Family Office',
      name: 'Cha-R Family Office',
      size: 11,
      at: [604.4, 500.6],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-5-technical-recycling',
      tier: 'tier-5',
      region: 't4-recycling',
      x: 130.21,
      y: 468.59,
      w: 86.21,
      h: 39.41,
      label: '',
      name: 'Technical & Recycling Level',
      size: 0,
      at: [173.3, 488.3],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-4-recycling-sewage-facilities',
      tier: 'tier-4',
      region: 't4-recycling',
      x: 819.88,
      y: 379.92,
      w: 77.59,
      h: 39.41,
      label: '',
      name: 'Recycling & Sewage Facilities',
      size: 0,
      at: [858.7, 399.6],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-3-aft-corridor',
      tier: 'tier-3',
      region: null,
      x: 768.15,
      y: 301.1,
      w: 60.35,
      h: 29.56,
      label: 'Aft Corridor',
      name: 'Aft Corridor',
      size: 8,
      at: [798.3, 318.5],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-3-forward-corridor',
      tier: 'tier-3',
      region: null,
      x: 75.04,
      y: 301.1,
      w: 55.17,
      h: 29.56,
      label: '',
      name: 'Forward Corridor',
      size: 0,
      at: [102.6, 315.9],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-central-passage',
      tier: 'tier-4',
      region: 'tier-4-central-passage',
      x: 354.35,
      y: 397.16,
      w: 68.97,
      h: 22.17,
      label: '',
      name: 'Central Passage Tier 4–5',
      size: 0,
      at: [388.8, 408.2],
      cut: true,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-4-secondary-passage',
      tier: 'tier-4',
      region: null,
      x: 526.77,
      y: 397.16,
      w: 68.97,
      h: 22.17,
      label: '',
      name: 'Secondary Transport Route',
      size: 0,
      at: [561.3, 408.2],
      cut: true,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-2-bulkhead',
      tier: 'tier-2',
      region: 't2-security',
      x: 785.4,
      y: 217.35,
      w: 60.34,
      h: 24.63,
      label: '',
      name: 'Tier 2 Bulkhead',
      size: 0,
      at: [815.6, 229.7],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-2-aft-corridor',
      tier: 'tier-2',
      region: null,
      x: 733.67,
      y: 217.35,
      w: 51.73,
      h: 24.63,
      label: '',
      name: 'Aft Corridor',
      size: 0,
      at: [759.5, 229.7],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-aft-corridor',
      tier: 'tier-5',
      region: null,
      x: 681.95,
      y: 485.83,
      w: 51.72,
      h: 22.17,
      label: '',
      name: 'Aft Corridor',
      size: 0,
      at: [707.8, 496.9],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-aft-promenade',
      tier: 'tier-1',
      region: null,
      x: 750.91,
      y: 128.68,
      w: 34.49,
      h: 24.63,
      label: '',
      name: 'Aft Promenade',
      size: 0,
      at: [768.2, 141.0],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-princes-quarters-gate',
      tier: 'tier-1',
      region: null,
      x: 457.8,
      y: 128.68,
      w: 34.49,
      h: 24.63,
      label: '',
      name: "Princes' Quarters Gate",
      size: 0,
      at: [475.0, 141.0],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-2-main-corridor',
      tier: 'tier-2',
      region: null,
      x: 475.04,
      y: 217.35,
      w: 34.49,
      h: 24.63,
      label: '',
      name: 'Main Corridor',
      size: 0,
      at: [492.3, 229.7],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-royal-approach',
      tier: 'tier-1',
      region: null,
      x: 302.63,
      y: 128.68,
      w: 34.48,
      h: 24.63,
      label: '',
      name: 'Banquet Hall Vestibule',
      size: 0,
      at: [319.9, 141.0],
      cut: true,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-3-bulkhead-access',
      tier: 'tier-3',
      region: null,
      x: 47.45,
      y: 301.1,
      w: 27.59,
      h: 29.56,
      label: '',
      name: 'Emergency Bulkhead to Tier 2',
      size: 0,
      at: [61.2, 315.9],
      cut: true,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-4-forward-corridor',
      tier: 'tier-4',
      region: null,
      x: 61.24,
      y: 397.16,
      w: 34.49,
      h: 22.17,
      label: '',
      name: 'Forward Corridor',
      size: 0,
      at: [78.5, 408.2],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-2-forward-corridor',
      tier: 'tier-2',
      region: null,
      x: 185.38,
      y: 217.35,
      w: 31.04,
      h: 24.63,
      label: '',
      name: 'Forward Corridor',
      size: 0,
      at: [200.9, 229.7],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-4-aft-corridor',
      tier: 'tier-4',
      region: null,
      x: 785.4,
      y: 397.16,
      w: 34.48,
      h: 22.17,
      label: '',
      name: 'Aft Corridor',
      size: 0,
      at: [802.6, 408.2],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-forward-corridor',
      tier: 'tier-5',
      region: null,
      x: 216.42,
      y: 485.83,
      w: 34.48,
      h: 22.17,
      label: '',
      name: 'Forward Corridor',
      size: 0,
      at: [233.7, 496.9],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-5-transverse-corridor',
      tier: 'tier-5',
      region: null,
      x: 492.29,
      y: 485.83,
      w: 34.48,
      h: 22.17,
      label: '',
      name: 'Transverse Corridor',
      size: 0,
      at: [509.5, 496.9],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1010',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1010',
      x: 633.91,
      y: 128.68,
      w: 24.64,
      h: 24.63,
      label: '',
      name: 'Room 1010 (Kacho)',
      size: 0,
      at: [646.2, 141.0],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1002',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1002',
      x: 500.91,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Room 1002 (Camilla)',
      size: 0,
      at: [513.2, 141.0],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1004',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1004',
      x: 534.16,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Room 1004 (Tserriednich)',
      size: 0,
      at: [546.5, 141.0],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1006',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1006',
      x: 567.41,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Room 1006 (Tyson)',
      size: 0,
      at: [579.7, 141.0],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1008',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1008',
      x: 600.66,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Room 1008 (Salé-salé)',
      size: 0,
      at: [613.0, 141.0],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1012',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1012',
      x: 667.17,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Room 1012 (Momoze)',
      size: 0,
      at: [679.5, 141.0],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-sector-room-1014',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector-room-1014',
      x: 700.42,
      y: 128.68,
      w: 24.63,
      h: 24.63,
      label: '',
      name: 'Room 1014 (Woble)',
      size: 0,
      at: [712.7, 141.0],
      cut: true,
      through: false,
      inferred: false,
    },
    {
      id: 'tier-1-c-aft-passage',
      tier: 'tier-1-c',
      region: null,
      x: 750.91,
      y: 74.0,
      w: 29.56,
      h: 14.78,
      label: '',
      name: 'Aft Passage',
      size: 0,
      at: [765.7, 81.4],
      cut: true,
      through: true,
      inferred: true,
    },
    {
      id: 'tier-1-royal-residential-corridor-aft',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 733.67,
      y: 128.68,
      w: 17.24,
      h: 24.63,
      label: '',
      name: "Guards' Round (aft)",
      size: 0,
      at: [742.3, 141.0],
      cut: true,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-1',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 492.29,
      y: 128.68,
      w: 8.62,
      h: 24.63,
      label: '',
      name: 'Cross Gap 1',
      size: 0,
      at: [496.6, 141.0],
      cut: true,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-2',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 525.54,
      y: 128.68,
      w: 8.62,
      h: 24.63,
      label: '',
      name: 'Cross Gap 2',
      size: 0,
      at: [529.8, 141.0],
      cut: true,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-3',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 558.79,
      y: 128.68,
      w: 8.62,
      h: 24.63,
      label: '',
      name: 'Cross Gap 3',
      size: 0,
      at: [563.1, 141.0],
      cut: true,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-4',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 592.04,
      y: 128.68,
      w: 8.62,
      h: 24.63,
      label: '',
      name: 'Cross Gap 4',
      size: 0,
      at: [596.3, 141.0],
      cut: true,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-5',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 625.29,
      y: 128.68,
      w: 8.62,
      h: 24.63,
      label: '',
      name: 'Cross Gap 5',
      size: 0,
      at: [629.6, 141.0],
      cut: true,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-6',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 658.55,
      y: 128.68,
      w: 8.62,
      h: 24.63,
      label: '',
      name: 'Cross Gap 6',
      size: 0,
      at: [662.9, 141.0],
      cut: true,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-7',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 691.8,
      y: 128.68,
      w: 8.62,
      h: 24.63,
      label: '',
      name: 'Cross Gap 7',
      size: 0,
      at: [696.1, 141.0],
      cut: true,
      through: true,
      inferred: false,
    },
    {
      id: 'tier-1-royal-residential-cross-gap-8',
      tier: 'tier-1',
      region: 'tier-1-royal-residential-sector',
      x: 725.05,
      y: 128.68,
      w: 8.62,
      h: 24.63,
      label: '',
      name: 'Cross Gap 8',
      size: 0,
      at: [729.4, 141.0],
      cut: true,
      through: true,
      inferred: false,
    },
  ]

  /**
   * A deck of the tier-1 liner is labelled to starboard and on one line: three
   * tiers-worth of tab on the port margin, three and a half metres apart, is
   * three labels written over each other.
   */
  const decks = [
    {
      id: 'tier-1-c',
      name: 'Pont 1 · Pont des hôtes',
      child: true,
      x0: 477.51,
      x1: 795.25,
      floor: 88.78,
      ceiling: 74.0,
      elevation: 85.1,
    },
    {
      id: 'tier-1-b',
      name: 'Pont 1 · Pont de la garnison',
      child: true,
      x0: 322.33,
      x1: 795.25,
      floor: 106.02,
      ceiling: 91.24,
      elevation: 81.6,
    },
    {
      id: 'tier-1',
      name: 'Pont 1',
      child: false,
      x0: 130.21,
      x1: 819.88,
      floor: 153.31,
      ceiling: 128.68,
      elevation: 72,
    },
    {
      id: 'tier-2',
      name: 'Pont 2',
      child: false,
      x0: 95.73,
      x1: 854.36,
      floor: 241.98,
      ceiling: 217.35,
      elevation: 54,
    },
    {
      id: 'tier-3',
      name: 'Pont 3',
      child: false,
      x0: 44.0,
      x1: 906.09,
      floor: 330.66,
      ceiling: 301.1,
      elevation: 36,
    },
    {
      id: 'tier-4',
      name: 'Pont 4',
      child: false,
      x0: 44.0,
      x1: 906.09,
      floor: 419.33,
      ceiling: 397.16,
      elevation: 18,
    },
    {
      id: 'tier-5',
      name: 'Pont 5',
      child: false,
      x0: 130.21,
      x1: 733.67,
      floor: 508.0,
      ceiling: 485.83,
      elevation: 0,
    },
  ]

  const gaps = [
    {
      id: 'tier-5-tier-4',
      x: 130.21,
      y: 419.33,
      w: 603.46,
      h: 66.5,
      metres: 13.5,
    },
    {
      id: 'tier-4-tier-3',
      x: 44.0,
      y: 330.66,
      w: 862.09,
      h: 66.5,
      metres: 13.5,
    },
    {
      id: 'tier-3-tier-2',
      x: 95.73,
      y: 241.98,
      w: 758.63,
      h: 59.12,
      metres: 12,
    },
    {
      id: 'tier-2-tier-1',
      x: 130.21,
      y: 153.31,
      w: 689.67,
      h: 64.04,
      metres: 13,
    },
    {
      id: 'tier-1-tier-1-b',
      x: 322.33,
      y: 106.02,
      w: 472.92,
      h: 22.66,
      metres: 4.6,
    },
  ]

  /**
   * The liner over tier 1, open at the top edge of the drawing rather than
   * closed at a height. It is the only band here that says how far up the ship
   * goes by refusing to say it.
   */
  const superstructure = {
    x: 477.51,
    y: 0.0,
    w: 317.74,
    h: 74.0,
  }

  const waterline = 389.77

  /**
   * A room on the section opens the deck it belongs to and then itself, which
   * is the same two steps a reader takes by hand: the section is the way in to
   * a deck, not a replacement for it.
   */
  function open(room: Room) {
    mapState.selectTier(room.tier)
    if (room.region) mapState.selectLocation(room.region)
  }

  function openWithKeyboard(event: KeyboardEvent, room: Room) {
    if (event.key !== 'Enter' && event.key !== ' ') return
    event.preventDefault()
    event.stopPropagation()
    open(room)
  }

  function openDeck(tierId: string) {
    mapState.selectTier(tierId)
  }

  function openDeckWithKeyboard(event: KeyboardEvent, tierId: string) {
    if (event.key !== 'Enter' && event.key !== ' ') return
    event.preventDefault()
    openDeck(tierId)
  }
</script>

<svg viewBox="0 0 1000 600" class="w-full h-full text-[#FFFFF0]">
  <defs>
    <style>
      .sea {
        fill: #0f172a;
      }
      .hull {
        fill: #1a0f0f;
        stroke: #ffd700;
        stroke-width: 3;
      }
      .room {
        fill: #2a1515;
        stroke: #fffff0;
        stroke-width: 1;
        transition: fill 0.2s;
      }
      .room.behind {
        fill: #221010;
        stroke: #fffff0;
        stroke-opacity: 0.18;
        stroke-width: 0.5;
        fill-opacity: 0.55;
      }
      .room.clickable {
        cursor: pointer;
      }
      .room.clickable:hover {
        fill: #3d1c1c;
      }
      g[role='button']:focus .room {
        stroke: #ffd700;
        stroke-width: 2;
      }
      .room.through {
        fill: #150b0b;
        stroke: #ffd700;
        stroke-opacity: 0.35;
        stroke-dasharray: 4 4;
      }
      .room.inferred {
        fill: #16171c;
        stroke: #9dc4e0;
        stroke-opacity: 0.4;
      }
      .gap {
        fill: url(#unbuilt);
        stroke: #ffd700;
        stroke-opacity: 0.12;
        stroke-width: 0.5;
      }
      .deck-rule {
        stroke: #ffd700;
        stroke-opacity: 0.45;
        stroke-width: 1;
        stroke-dasharray: 2 5;
      }
      .deck-tab {
        cursor: pointer;
      }
      .deck-tab text {
        fill: #ffd700;
        font-family: sans-serif;
        font-size: 12px;
        letter-spacing: 1px;
      }
      .deck-tab:hover text {
        fill: #fffff0;
      }
      .label {
        fill: #fffff0;
        font-family: sans-serif;
        pointer-events: none;
        text-anchor: middle;
      }
      .note {
        fill: #fffff0;
        fill-opacity: 0.5;
        font-family: sans-serif;
        font-size: 10px;
        pointer-events: none;
      }
      .waterline {
        stroke: #9dc4e0;
        stroke-opacity: 0.55;
        stroke-width: 1.5;
        stroke-dasharray: 8 6;
      }
    </style>
    <!-- The liner fades out toward the top edge rather than stopping at a line:
         the drawing does not know how tall it is, and says so. -->
    <linearGradient id="open-top" x1="0" y1="1" x2="0" y2="0">
      <stop offset="0" stop-color="#fff" stop-opacity="1" />
      <stop offset="1" stop-color="#fff" stop-opacity="0" />
    </linearGradient>
    <mask id="fade-up">
      <rect x="477.51" y="0.0" width="317.74" height="74.0" fill="url(#open-top)" />
    </mask>
    <pattern
      id="unbuilt"
      width="6"
      height="6"
      patternTransform="rotate(45)"
      patternUnits="userSpaceOnUse"
    >
      <rect width="6" height="6" fill="#140d0d" />
      <line x1="0" y1="0" x2="0" y2="6" stroke="#ffd700" stroke-opacity="0.13" stroke-width="1.5" />
    </pattern>
  </defs>

  <rect class="sea" x="0" y={waterline} width="1000" height={600 - waterline} />

  <polygon
    class="hull"
    points="130.21,508.0 130.21,485.83 44.0,419.33 44.0,397.16 44.0,330.66 44.0,301.1 95.73,241.98 95.73,217.35 130.21,153.31 130.21,128.68 322.33,106.02 322.33,91.24 477.51,88.78 477.51,74.0 795.25,74.0 795.25,88.78 795.25,91.24 795.25,106.02 819.88,128.68 819.88,153.31 854.36,217.35 854.36,241.98 906.09,301.1 906.09,330.66 906.09,397.16 906.09,419.33 733.67,485.83 733.67,508.0"
  />

  <rect
    class="gap"
    mask="url(#fade-up)"
    x={superstructure.x}
    y={superstructure.y}
    width={superstructure.w}
    height={superstructure.h}
  />

  {#each gaps as gap (gap.id)}
    <rect class="gap" x={gap.x} y={gap.y} width={gap.w} height={gap.h} />
  {/each}

  <g id="section-rooms">
    {#each rooms as room (room.id)}
      {#if room.cut && room.region}
        <g
          role="button"
          tabindex="0"
          aria-label={room.name}
          onclick={() => open(room)}
          onkeydown={(event) => openWithKeyboard(event, room)}
        >
          <title>{room.name}</title>
          <rect
            class="room clickable"
            class:through={room.through}
            class:inferred={room.inferred}
            x={room.x}
            y={room.y}
            width={room.w}
            height={room.h}
          />
        </g>
      {:else}
        <rect
          class="room"
          class:behind={!room.cut}
          class:through={room.through}
          class:inferred={room.inferred}
          x={room.x}
          y={room.y}
          width={room.w}
          height={room.h}
        />
      {/if}
    {/each}

    {#each rooms.filter((room) => room.size > 0) as room (room.id)}
      <text class="label" x={room.at[0]} y={room.at[1]} font-size={room.size}>{room.label}</text>
    {/each}
  </g>

  <line class="waterline" x1="0" y1={waterline} x2="1000" y2={waterline} />

  <!-- The eye of the ch. 349 page: low, forward, and opening nothing. -->
  <circle
    cx="199.18"
    cy="370.07"
    r="24.6"
    fill="#050505"
    stroke="#ffd700"
    stroke-width="2"
    pointer-events="none"
  />
  <circle cx="199.18" cy="370.07" r="9.5" fill="#fffff0" pointer-events="none" />

  {#each decks as deck (deck.id)}
    <line class="deck-rule" x1={deck.x0} y1={deck.floor} x2={deck.x1} y2={deck.floor} />
    <g
      class="deck-tab"
      role="button"
      tabindex="0"
      aria-label={deck.name}
      onclick={() => openDeck(deck.id)}
      onkeydown={(event) => openDeckWithKeyboard(event, deck.id)}
    >
      {#if deck.child}
        <text x="1000" y={deck.ceiling + 11} text-anchor="end" font-size="10"
          >{deck.name} · {deck.elevation} m</text
        >
      {:else}
        <text x="6" y={deck.ceiling + 12}>{deck.name}</text>
        <text x="6" y={deck.ceiling + 25} font-size="9" fill-opacity="0.55">{deck.elevation} m</text
        >
      {/if}
    </g>
  {/each}

  {#each gaps as gap (gap.id)}
    {#if gap.h > 26}
      <text class="note" x={gap.x + gap.w / 2} y={gap.y + gap.h / 2 + 3} text-anchor="middle"
        >{$t.ship.unmodelledDecks(gap.metres)}</text
      >
    {/if}
  {/each}

  <text
    class="note"
    x={superstructure.x + superstructure.w / 2}
    y={superstructure.y + superstructure.h - 12}
    text-anchor="middle">{$t.ship.superstructure}</text
  >
</svg>
