import { format, resolveConfig } from 'prettier'
import type { ArenaContract } from '@black-whale/nen-engine'
import { literal } from '../hatsu/emit.js'

/**
 * Renders the compiled arena contracts as TypeScript.
 *
 * Committed rather than built, for the reason `hatsu/emit.ts` gives: a duel
 * that suddenly costs six aura instead of eighteen is a change a reader should
 * see in the diff. `--check` in CI is what keeps it honest.
 */

const HEADER = `// Generated by \`pnpm --filter @black-whale/canon-compiler compile:hatsu\`.
// Do not edit: rerun the compiler. The facts come from each module's \`arena\`
// block, beside the rule that enforces them — edit those.

import type { ArenaContract } from '@black-whale/nen-engine'
`

function renderContract(contract: ArenaContract): string {
  const fields: Array<[string, string]> = [
    ['id', literal(contract.id)],
    ['effect', literal(contract.effect)],
    ['cost', String(contract.cost)],
    ['persistent', String(contract.persistent)],
    ['condition', literal(contract.condition)],
    ['risk', literal(contract.risk)],
  ]
  if (contract.mechanic) fields.push(['mechanic', literal(contract.mechanic)])
  const body = fields.map(([key, value]) => `    ${key}: ${value},`).join('\n')
  return `  {\n${body}\n  },`
}

export async function emitArenaContracts(
  contracts: readonly ArenaContract[],
  filepath: string,
): Promise<string> {
  const entries = contracts.map(renderContract).join('\n')
  const source = `${HEADER}
/**
 * Every ability the arena can cast, with what it costs and risks.
 *
 * The subset carrying a \`mechanic\` is the Black Whale roster the mode is
 * built around; the rest are the abilities it inherited from the earlier arcs.
 */
export const ARENA_CONTRACTS: ArenaContract[] = [
${entries}
]
`
  const config = await resolveConfig(filepath)
  return format(source, { ...config, filepath })
}
