import { MANGA_APARTMENT_VIEWS } from './mangaApartmentViews'
import { MANGA_CHA_R_VIEWS } from './mangaChaRViews'
import { mangaView as view, type MangaView } from './mangaViewModel'

export type { MangaCastStaging, MangaView } from './mangaViewModel'

/**
 * A catalogue of specific camera angles that reproduce panels from the manga.
 * The walk can jump the visitor here so they see exactly what the drawing shows.
 */
export const MANGA_VIEWS: MangaView[] = [
  view({
    id: 'princes-burial-chamber-overhead',
    spaceId: 'tier-1-princes-burial-chamber-rotunda',
    at: [0, 0],
    target: [0, 0],
    pitch: -Math.PI / 2, // overhead view (top-down)
    eyeHeight: 40,
    chapter: 383,
    volume: 37,
    pages: '18-19',
    label: 'The 14 coffins around the central machine',
    labelFr: 'Les 14 cercueils autour de la machine centrale',
  }),
  {
    id: 'luzurus-smoking-area',
    chapter: 359,
    space: 'tier-1-royal-residential-sector-room-1007-living',
    label: 'Luzurus and Basho smoking hookah in the raised tatami area',
    labelFr: "Luzurus et Basho fumant le narguilé dans l'espace surélevé",
    camera: {
      position: [3, 3, 1.2],
      target: [6, 3, 0.5],
      fov: 60,
    },
  },
  {
    id: 'kacho-fugetsu-vestibule-farewell',
    chapter: 359,
    space: 'tier-1-banquet-hall-vestibule',
    label: 'Kacho and Fugetsu waving goodbye across the banquet hall vestibule doors',
    labelFr:
      'Kacho et Fugetsu se disant au revoir à travers les portes du sas de la salle des fêtes',
    camera: {
      position: [-50, -5.5, 1.5],
      target: [-50, -3.5, 1.5],
      fov: 60,
    },
  },
  view({
    id: 'princely-quarter-aerial-plan',
    spaceId: 'tier-1-royal-residential-cross-gap-1',
    at: [10.5, 4.9],
    target: [10.5, 30],
    pitch: -0.95,
    eyeHeight: 36,
    chapter: 363,
    volume: 35,
    pages: '49–50',
    label: 'Aerial plan of the princely residential quarter, apartments 1 to 14',
    labelFr: 'Plan aérien du quartier résidentiel des princes, appartements 1 à 14',
    triggerSpaceIds: [
      'tier-1-royal-residential-corridor-port',
      'tier-1-royal-residential-corridor-starboard',
      'tier-1-royal-residential-corridor-aft',
      ...Array.from({ length: 8 }, (_, index) => `tier-1-royal-residential-cross-gap-${index + 1}`),
    ],
  }),
  view({
    id: 'beyond-cell-bars',
    spaceId: 'tier-1-vvip-prison-beyond-cell',
    at: [-2.2, 0],
    target: [-6.3, 0.4],
    pitch: -0.03,
    chapter: 350,
    volume: 34,
    label: 'Beyond, seen through the bars of the high-security cell',
    labelFr: 'Beyond vu à travers les barreaux de la cellule de haute sécurité',
  }),
  view({
    id: 'beyond-cell-aerial-plan',
    spaceId: 'tier-1-vvip-prison-beyond-watch',
    at: [0, 0],
    target: [0, -1],
    pitch: -1.5,
    eyeHeight: 14,
    chapter: 359,
    volume: 34,
    label: "Aerial plan of Beyond's high-security cell and the Zodiac watch post",
    labelFr: 'Plan aérien de la cellule haute sécurité de Beyond et du poste des Zodiaques',
  }),
  view({
    id: 'vip-detention-aerial-plan',
    spaceId: 'tier-1-vip-jail-corridor',
    at: [0, 0],
    target: [0, -1],
    pitch: -1.5,
    eyeHeight: 15,
    chapter: 350,
    volume: 34,
    label: 'Aerial plan of the VIP detention block and its four cells',
    labelFr: 'Plan aérien du quartier de détention VIP et de ses quatre cellules',
    triggerSpaceIds: [
      'tier-1-vip-jail-cell-first-class',
      'tier-1-vip-jail-cell-vip',
      'tier-1-vip-jail-cell-standard',
      'tier-1-vip-jail-cell-standard-2',
    ],
  }),
  view({
    id: 'woble-living-phone-wall',
    spaceId: 'tier-1-royal-residential-sector-room-1014-living',
    at: [1, 4.7],
    target: [8.9, 3.2],
    pitch: 0.01,
    chapter: 360,
    volume: 34,
    label: "Woble's living room, from the phone wall to the display furniture",
    labelFr: 'Le salon de Woble, du téléphone mural au mobilier de présentation',
  }),
  view({
    id: 'benjamin-living-guards',
    spaceId: 'tier-1-royal-residential-sector-room-1001-living',
    at: [0, 4.8],
    target: [-6.2, 1.8],
    pitch: -0.02,
    chapter: 362,
    volume: 35,
    label: "Benjamin's reception room and its guard line",
    labelFr: 'Le salon de réception de Benjamin et sa ligne de gardes',
  }),
  view({
    id: 'tserriednich-living-training',
    spaceId: 'tier-1-royal-residential-sector-room-1004-living',
    at: [0.2, 4.8],
    target: [-6.1, 1.7],
    pitch: -0.04,
    chapter: 362,
    volume: 35,
    label: "Tserriednich's Nen training room",
    labelFr: "La pièce d'entraînement au Nen de Tserriednich",
  }),
  view({
    id: 'tyson-living-audience',
    spaceId: 'tier-1-royal-residential-sector-room-1006-living',
    at: [0.4, 4.7],
    target: [-6, 1.7],
    pitch: -0.03,
    chapter: 362,
    volume: 35,
    label: "Tyson's audience room",
    labelFr: "Le salon d'audience de Tyson",
  }),
  view({
    id: 'luzurus-living-sofa',
    spaceId: 'tier-1-royal-residential-sector-room-1007-living',
    at: [-0.2, 4.8],
    target: [-6, 1.8],
    pitch: -0.03,
    chapter: 362,
    volume: 35,
    label: "Luzurus's sofa group",
    labelFr: 'Le groupe de canapés de Luzurus',
  }),
  view({
    id: 'zhang-lei-dining-oito',
    spaceId: 'tier-1-royal-residential-sector-room-1003-dining',
    at: [2.25, -0.65],
    target: [7.2, -2.8],
    pitch: -0.04,
    chapter: 365,
    volume: 35,
    label: 'Zhang Lei receiving Queen Oito across the long dining table',
    labelFr: 'Zhang Lei recevant la reine Oito devant la longue table sculptée',
  }),
  view({
    id: 'tubeppa-living-workstation',
    spaceId: 'tier-1-royal-residential-sector-room-1005-living',
    at: [2.8, 4.7],
    target: [9.3, 2.9],
    pitch: 0,
    chapter: 366,
    volume: 35,
    label: "Tubeppa's workstation and equation-covered boards",
    labelFr: 'Le poste de travail de Tubeppa et ses tableaux couverts d’équations',
  }),
  view({
    id: 'momoze-bedroom-vent',
    spaceId: 'tier-1-royal-residential-sector-room-1012-bedroom',
    at: [3.7, 6.35],
    target: [-7.5, 8.45],
    pitch: -0.07,
    chapter: 367,
    volume: 35,
    label: "Momoze's bed and the ventilation grille used by her attacker",
    labelFr: "Le lit de Momoze et la grille d'aération empruntée par son assassin",
  }),
  view({
    id: 'marayam-living-vent',
    spaceId: 'tier-1-royal-residential-sector-room-1013-living',
    at: [3.7, 4.7],
    target: [-9.5, -0.7],
    pitch: 0.03,
    chapter: 367,
    volume: 35,
    label: "Marayam's living room and the watched ventilation grille",
    labelFr: "Le salon de Marayam et la grille d'aération sous surveillance",
  }),
  view({
    id: 'woble-kitchen-counter',
    spaceId: 'tier-1-royal-residential-sector-room-1014-kitchen',
    at: [2.15, -6.3],
    target: [6.7, -9.65],
    pitch: -0.02,
    chapter: 367,
    volume: 35,
    label: "Woble's kitchen counter beneath the glass-fronted cupboards",
    labelFr: 'Le plan de travail de Woble sous les éléments hauts vitrés',
  }),
  view({
    id: 'burial-rotunda-caskets',
    spaceId: 'tier-1-princes-burial-chamber-rotunda',
    at: [0, -9.25],
    target: [0, 0],
    pitch: 0.08,
    chapter: 371,
    volume: 36,
    label: 'The fourteen radial caskets of the succession-war burial chamber',
    labelFr: 'Les quatorze cercueils en rayon de la chambre funéraire de la succession',
  }),
  view({
    id: 'supreme-court-bench-seal',
    spaceId: 'tier-1-supreme-court',
    at: [112, 38.5],
    target: [122.35, 38.5],
    pitch: 0.03,
    chapter: 371,
    volume: 36,
    pages: '9',
    label: 'The Supreme Court bench beneath the circular judicial seal',
    labelFr: 'Le banc de la Cour suprême sous le sceau judiciaire circulaire',
  }),
  view({
    id: 'woble-dining-guards',
    spaceId: 'tier-1-royal-residential-sector-room-1014-dining',
    at: [2.15, -4.95],
    target: [8.3, -2.6],
    pitch: -0.04,
    chapter: 371,
    volume: 36,
    label: "Woble's guards gathered around the two meal-covered tables",
    labelFr: 'Les gardes de Woble réunis autour des deux longues tables de repas',
  }),
  view({
    id: 'kacho-living-homework',
    spaceId: 'tier-1-royal-residential-sector-room-1010-living',
    at: [0.8, 4.75],
    target: [-7.8, -2.35],
    pitch: -0.01,
    chapter: 376,
    volume: 36,
    label: 'Kacho studying beneath the coffered ceiling',
    labelFr: 'Kacho travaillant sous le plafond à caissons',
  }),
  view({
    id: 'kacho-kitchen-cabinet',
    spaceId: 'tier-1-royal-residential-sector-room-1010-kitchen',
    at: [2.15, -6.3],
    target: [6.8, -9.65],
    pitch: -0.05,
    chapter: 376,
    volume: 36,
    label: "Kacho's kitchen and the lower cupboard named in Melody's Morse code",
    labelFr: 'La cuisine de Kacho et le placard bas désigné par le morse de Senritsu',
  }),
  view({
    id: 'nasubi-living-mantel',
    spaceId: 'tier-1-king-living-quarters-living',
    at: [0, 7.15],
    target: [0, -7.45],
    pitch: -0.07,
    chapter: 382,
    eventSequence: 1,
    volume: 37,
    pages: '29–30',
    label: "Nasubi's salon facing the monumental painting and ornamented mantel",
    labelFr: 'Le salon de Nasubi face au tableau monumental et au manteau ornementé',
    // Ch. 382, pp. 29–30: Nasubi occupies the left seating group,
    // Halkenburg crosses the open floor at right, while Nasubi's Guardian
    // Spirit Beast occupies the far edge. This blocking is part of the panel
    // just as much as the lens:
    // leaving the generic hashed stations in place put the King outside it.
    staging: [
      {
        characterId: 'nasubi-hui-guo-rou',
        at: [-5, -0.15],
        heading: 0,
        pose: 'seated',
      },
      {
        characterId: 'prince-halkenburg',
        at: [5.1, -1.35],
        heading: -1.45,
        pose: 'idle',
      },
    ],
  }),
  view({
    id: 'lifeboat-round-hatch',
    spaceId: 'tier-1-lifeboats-port-pod-cabin',
    at: [1.75, 1.25],
    target: [0, -1.7],
    pitch: 0.03,
    chapter: 383,
    volume: 37,
    pages: '60–65',
    label: 'The ribbed lifeboat cabin facing its round hatch and console',
    labelFr: 'La cabine nervurée de la capsule face à son écoutille ronde et sa console',
  }),
  view({
    id: 'royal-army-briefing-audience',
    spaceId: 'tier-4-royal-army-conference-room-floor',
    at: [0, 6.5],
    target: [0, -5.2],
    pitch: 0.05,
    chapter: 380,
    volume: 36,
    pages: '189',
    label: 'The royal-army briefing from behind the U-shaped conference table',
    labelFr: 'Le briefing de l’armée royale derrière la table de conférence en U',
    staging: [
      {
        characterId: 'mizaistom-nana',
        at: [0.8, -3.25],
        heading: Math.PI,
        pose: 'idle',
      },
    ],
  }),
  view({
    id: 'xi-yu-office-aerial-plan',
    spaceId: 'tier-4-xi-yu-family-office-meeting-room',
    at: [0, 1],
    target: [0, 0],
    pitch: -1.5,
    eyeHeight: 16,
    chapter: 380,
    volume: 36,
    label: 'Aerial plan of the published Xi-Yu office and guarded entrance',
    labelFr: 'Plan aérien du bureau Xi-Yu publié et de son entrée gardée',
    triggerSpaceIds: ['tier-4-xi-yu-family-office-entrance'],
  }),
  view({
    id: 'cineplex-establishing-shot',
    spaceId: 'tier-3-cineplex-screen-corridor',
    triggerSpaceIds: ['tier-3-cineplex-concession', 'tier-3-cineplex-ticket-desk'],
    at: [0, -4.25],
    target: [0, 9.8],
    pitch: 0.02,
    chapter: 393,
    volume: 38,
    label: 'The cineplex hall between the concession stand, ticket desks and screens',
    labelFr: 'Le hall du cinéma entre la confiserie, les guichets et les salles',
  }),
  view({
    id: 'room-3101-bunks-storage',
    spaceId: 'tier-3-residential-room-3101-living',
    at: [1, 0],
    target: [-6.25, 0.45],
    pitch: -0.02,
    chapter: 393,
    volume: 38,
    pages: '64–67',
    label: 'Room 3101 facing the stacked bunk and open wall storage',
    labelFr: 'La chambre 3101 face au lit superposé et au rangement mural ouvert',
  }),
  view({
    id: 'room-3101-bathroom-trap',
    spaceId: 'tier-3-residential-room-3101-living',
    at: [-4.7, 2.8],
    target: [2, 0],
    pitch: -0.03,
    chapter: 398,
    volume: 38,
    pages: '150–153',
    label: 'Room 3101 facing the Heil-Ly bathroom trap',
    labelFr: 'La chambre 3101 face au piège Heil-Ly de la salle de bains',
  }),
  view({
    id: 'first-class-cabins-aerial-plan',
    spaceId: 'tier-3-residential-first-class-companionway',
    at: [0, 2],
    target: [0, 1],
    pitch: -1.5,
    eyeHeight: 34,
    chapter: 393,
    volume: 38,
    label: 'Aerial plan of the published first-class cabins',
    labelFr: 'Plan aérien des cabines de première classe publiées',
    triggerSpaceIds: [
      'tier-3-residential-first-class-hallway',
      'tier-3-residential-first-class-upper-corridor',
    ],
    visibleSpaceIds: [
      'tier-3-residential-first-class-suite-1',
      'tier-3-residential-first-class-suite-1-wc',
      'tier-3-residential-first-class-suite-2',
      'tier-3-residential-first-class-suite-2-wc',
      'tier-3-residential-first-class-suite-3',
      'tier-3-residential-first-class-suite-3-wc',
      'tier-3-residential-first-class-upper-cabin-1',
      'tier-3-residential-first-class-upper-cabin-1-wc',
      'tier-3-residential-first-class-upper-cabin-2',
      'tier-3-residential-first-class-upper-cabin-2-wc',
      'tier-3-residential-first-class-upper-cabin-3',
      'tier-3-residential-first-class-upper-cabin-3-wc',
    ],
  }),
  view({
    id: 'unma-nursery-salon',
    spaceId: 'tier-1-queens-living-quarters-room-01',
    at: [-36.2, 7.9],
    target: [-33.6, 12.5],
    pitch: 0.01,
    chapter: 403,
    volume: 39,
    label: 'Queen Unma in her formal salon with the nursery visible behind her',
    labelFr: 'La reine Unma dans son salon d’apparat, avec la nursery visible derrière elle',
  }),
  ...MANGA_CHA_R_VIEWS,
  view({
    id: 'morena-office-negotiation-game',
    spaceId: 'tier-2-heilly-secret-hideout-office',
    at: [14.4, 0.55],
    target: [11.9, 6.45],
    pitch: -0.02,
    chapter: 407,
    volume: 39,
    label: 'Morena’s negotiation table between the wall couch and the two consoles',
    labelFr: 'La table de négociation de Morena entre le canapé mural et les deux consoles',
    staging: [
      {
        characterId: 'morena-prudo',
        at: [12.08, 1.6],
        heading: 0,
        pose: 'seated',
      },
      {
        characterId: 'borksen',
        at: [12.08, 3.7],
        heading: Math.PI,
        pose: 'seated',
      },
    ],
  }),
  view({
    id: 'heilly-hideout-aerial-plan',
    spaceId: 'tier-2-heilly-secret-hideout-corridor',
    at: [-1.6, -3.5],
    target: [-1.6, -4.5],
    pitch: -1.48,
    eyeHeight: 28,
    chapter: 399,
    volume: 38,
    label: 'Aerial plan of the published Heil-Ly hideout rooms',
    labelFr: 'Plan aérien des pièces publiées de la planque Heil-Ly',
    triggerSpaceIds: [
      'tier-2-heilly-secret-hideout-processing',
      'tier-2-heilly-secret-hideout-laundry',
      'tier-2-heilly-secret-hideout-communal',
    ],
    visibleSpaceIds: [
      'tier-2-heilly-secret-hideout-processing',
      'tier-2-heilly-secret-hideout-laundry',
      'tier-2-heilly-secret-hideout-communal',
      'tier-2-heilly-secret-hideout-office',
    ],
  }),
  ...MANGA_APARTMENT_VIEWS,
]

export function viewsForSpace(spaceId: string | null): MangaView[] {
  if (!spaceId) return []
  return MANGA_VIEWS.filter(
    (view) => view.spaceId === spaceId || view.triggerSpaceIds?.includes(spaceId),
  )
}

export function mangaViewById(id: string | null): MangaView | null {
  if (!id) return null
  return MANGA_VIEWS.find((view) => view.id === id) ?? null
}
