import { mangaView as view, type MangaView } from './mangaViewModel'

export const MANGA_GENERAL_VIEWS: MangaView[] = [
  view({
    id: 'supreme-court-camilla-hearing',
    chapter: 379,
    spaceId: 'tier-1-supreme-court',
    label: 'Supreme Court hearing regarding the arrest of Prince Camilla',
    labelFr: "Audience de la Cour suprême concernant l'arrestation de la Princesse Camilla",
    at: [98, 3.5],
    target: [118, 1.0],
    pitch: 0,
    eyeHeight: 38.5,
  }),
  view({
    id: 'princes-burial-chamber-overhead',
    spaceId: 'tier-1-princes-burial-chamber-rotunda',
    at: [0, 0],
    target: [0, 0],
    pitch: -1.57, // overhead view (top-down)
    eyeHeight: 40,
    chapter: 383,
    volume: 37,
    pages: '18-19',
    label: 'The 14 coffins around the central machine',
    labelFr: 'Les 14 cercueils autour de la machine centrale',
  }),
  view({
    id: 'central-dining-hall-troupe',
    spaceId: 'tier-5-central-dining-hall',
    at: [0, -10],
    target: [0, 0],
    pitch: -0.4,
    eyeHeight: 5,
    chapter: 377,
    volume: 36,
    pages: '105-106',
    label: 'The Phantom Troupe gathered at the raised platform',
    labelFr: 'La Brigade Fantôme réunie sur la plateforme centrale',
  }),
  view({
    id: 'luzurus-smoking-area',
    chapter: 359,
    spaceId: 'tier-1-royal-residential-sector-room-1007-living',
    label: 'Luzurus and Basho smoking hookah in the raised tatami area',
    labelFr: "Luzurus et Basho fumant le narguilé dans l'espace surélevé",
    at: [3, 1.2],
    target: [6, 0.5],
    pitch: -0.1,
    eyeHeight: 3,
  }),
  view({
    id: 'kacho-fugetsu-vestibule-farewell',
    chapter: 359,
    spaceId: 'tier-1-banquet-hall-vestibule',
    label: 'Kacho and Fugetsu waving goodbye across the banquet hall vestibule doors',
    labelFr:
      'Kacho et Fugetsu se disant au revoir à travers les portes du sas de la salle des fêtes',
    at: [-50, 1.5],
    target: [-50, 1.5],
    pitch: 0,
    eyeHeight: -5.5,
  }),
  view({
    id: 'princely-quarter-aerial-plan',
    spaceId: 'tier-1-royal-residential-cross-gap-1',
    at: [10.5, 4.9],
    target: [10.5, 30],
    pitch: -0.95,
    eyeHeight: 36,
    chapter: 363,
    volume: 35,
    pages: '49–50',
    label: 'Aerial plan of the princely residential quarter, apartments 1 to 14',
    labelFr: 'Plan aérien du quartier résidentiel des princes, appartements 1 à 14',
    triggerSpaceIds: [
      'tier-1-royal-residential-corridor-port',
      'tier-1-royal-residential-corridor-starboard',
      'tier-1-royal-residential-corridor-aft',
      ...Array.from({ length: 8 }, (_, index) => `tier-1-royal-residential-cross-gap-${index + 1}`),
    ],
  }),
  view({
    id: 'beyond-cell-bars',
    spaceId: 'tier-1-vvip-prison-beyond-cell',
    at: [-2.2, 0],
    target: [-6.3, 0.4],
    pitch: -0.03,
    chapter: 350,
    volume: 34,
    label: 'Beyond, seen through the bars of the high-security cell',
    labelFr: 'Beyond vu à travers les barreaux de la cellule de haute sécurité',
  }),
  view({
    id: 'beyond-cell-aerial-plan',
    spaceId: 'tier-1-vvip-prison-beyond-watch',
    at: [0, 0],
    target: [0, -1],
    pitch: -1.5,
    eyeHeight: 14,
    chapter: 359,
    volume: 34,
    label: "Aerial plan of Beyond's high-security cell and the Zodiac watch post",
    labelFr: 'Plan aérien de la cellule haute sécurité de Beyond et du poste des Zodiaques',
  }),
  view({
    id: 'vip-detention-aerial-plan',
    spaceId: 'tier-1-vip-jail-corridor',
    at: [0, 0],
    target: [0, -1],
    pitch: -1.5,
    eyeHeight: 15,
    chapter: 350,
    volume: 34,
    label: 'Aerial plan of the VIP detention block and its four cells',
    labelFr: 'Plan aérien du quartier de détention VIP et de ses quatre cellules',
    triggerSpaceIds: [
      'tier-1-vip-jail-cell-first-class',
      'tier-1-vip-jail-cell-vip',
      'tier-1-vip-jail-cell-standard',
      'tier-1-vip-jail-cell-standard-2',
    ],
  }),
  view({
    id: 'woble-living-phone-wall',
    spaceId: 'tier-1-royal-residential-sector-room-1014-living',
    at: [1, 4.7],
    target: [8.9, 3.2],
    pitch: 0.01,
    chapter: 360,
    volume: 34,
    label: "Woble's living room, from the phone wall to the display furniture",
    labelFr: 'Le salon de Woble, du téléphone mural au mobilier de présentation',
  }),
  view({
    id: 'benjamin-living-guards',
    spaceId: 'tier-1-royal-residential-sector-room-1001-living',
    at: [0, 4.8],
    target: [-6.2, 1.8],
    pitch: -0.02,
    chapter: 362,
    volume: 35,
    label: "Benjamin's reception room and its guard line",
    labelFr: 'Le salon de réception de Benjamin et sa ligne de gardes',
  }),
  view({
    id: 'tserriednich-living-training',
    spaceId: 'tier-1-royal-residential-sector-room-1004-living',
    at: [0.2, 4.8],
    target: [-6.1, 1.7],
    pitch: -0.04,
    chapter: 362,
    volume: 35,
    label: "Tserriednich's Nen training room",
    labelFr: "La pièce d'entraînement au Nen de Tserriednich",
  }),
  view({
    id: 'tyson-living-audience',
    spaceId: 'tier-1-royal-residential-sector-room-1006-living',
    at: [0.4, 4.7],
    target: [-6, 1.7],
    pitch: -0.03,
    chapter: 362,
    volume: 35,
    label: "Tyson's audience room",
    labelFr: "Le salon d'audience de Tyson",
  }),
  view({
    id: 'luzurus-living-sofa',
    spaceId: 'tier-1-royal-residential-sector-room-1007-living',
    at: [-0.2, 4.8],
    target: [-6, 1.8],
    pitch: -0.03,
    chapter: 362,
    volume: 35,
    label: "Luzurus's sofa group",
    labelFr: 'Le groupe de canapés de Luzurus',
  }),
  view({
    id: 'zhang-lei-dining-oito',
    spaceId: 'tier-1-royal-residential-sector-room-1003-dining',
    at: [2.25, -0.65],
    target: [7.2, -2.8],
    pitch: -0.04,
    chapter: 365,
    volume: 35,
    label: 'Zhang Lei receiving Queen Oito across the long dining table',
    labelFr: 'Zhang Lei recevant la reine Oito devant la longue table sculptée',
  }),
  view({
    id: 'tubeppa-living-workstation',
    spaceId: 'tier-1-royal-residential-sector-room-1005-living',
    at: [2.8, 4.7],
    target: [9.3, 2.9],
    pitch: 0,
    chapter: 366,
    volume: 35,
    label: "Tubeppa's workstation and equation-covered boards",
    labelFr: 'Le poste de travail de Tubeppa et ses tableaux couverts d’équations',
  }),
  view({
    id: 'momoze-bedroom-vent',
    spaceId: 'tier-1-royal-residential-sector-room-1012-bedroom',
    at: [3.7, 6.35],
    target: [-7.5, 8.45],
    pitch: -0.07,
    chapter: 367,
    volume: 35,
    label: "Momoze's bed and the ventilation grille used by her attacker",
    labelFr: "Le lit de Momoze et la grille d'aération empruntée par son assassin",
  }),
  view({
    id: 'marayam-living-vent',
    spaceId: 'tier-1-royal-residential-sector-room-1013-living',
    at: [3.7, 4.7],
    target: [-9.5, -0.7],
    pitch: 0.03,
    chapter: 367,
    volume: 35,
    label: "Marayam's living room and the watched ventilation grille",
    labelFr: "Le salon de Marayam et la grille d'aération sous surveillance",
  }),
  view({
    id: 'woble-kitchen-counter',
    spaceId: 'tier-1-royal-residential-sector-room-1014-kitchen',
    at: [2.15, -6.3],
    target: [6.7, -9.65],
    pitch: -0.02,
    chapter: 367,
    volume: 35,
    label: "Woble's kitchen counter beneath the glass-fronted cupboards",
    labelFr: 'Le plan de travail de Woble sous les éléments hauts vitrés',
  }),
  view({
    id: 'burial-rotunda-caskets',
    spaceId: 'tier-1-princes-burial-chamber-rotunda',
    at: [0, -9.25],
    target: [0, 0],
    pitch: 0.08,
    chapter: 371,
    volume: 36,
    label: 'The fourteen radial caskets of the succession-war burial chamber',
    labelFr: 'Les quatorze cercueils en rayon de la chambre funéraire de la succession',
  }),
  view({
    id: 'supreme-court-bench-seal',
    spaceId: 'tier-1-supreme-court',
    at: [112, 38.5],
    target: [122.35, 38.5],
    pitch: 0.03,
    chapter: 371,
    volume: 36,
    pages: '9',
    label: 'The Supreme Court bench beneath the circular judicial seal',
    labelFr: 'Le banc de la Cour suprême sous le sceau judiciaire circulaire',
  }),
  view({
]
