import { mangaView, type MangaView } from './mangaViewModel'

export const MANGA_CHA_R_VIEWS: MangaView[] = [
  mangaView({
    id: 'cha-r-emblem-three-doors',
    spaceId: 'tier-5-cha-r-family-office-main-office',
    at: [-4, -10],
    target: [-17, 1],
    pitch: 0.01,
    chapter: 379,
    volume: 36,
    label: 'The Cha-R emblem room and its treasure-chest, robot-faced and wooden doors',
    labelFr:
      'La salle à l’emblème Cha-R et ses portes en forme de coffre, à face de robot et en bois',
  }),
  mangaView({
    id: 'cha-r-bunks-bookshelves',
    spaceId: 'tier-5-cha-r-family-office-bedroom',
    at: [-11, 5.5],
    target: [-11, 9.3],
    pitch: -0.03,
    chapter: 379,
    volume: 36,
    label: 'The Cha-R compartment lined with stacked bunks and wall bookshelves',
    labelFr: 'Le compartiment Cha-R bordé de lits superposés et de bibliothèques murales',
    staging: [
      {
        characterId: 'feitan-portor',
        at: [-18, 7.1],
        heading: Math.PI,
        pose: 'idle',
      },
    ],
  }),
  mangaView({
    id: 'cha-r-cctv-monitor-room',
    spaceId: 'tier-5-cha-r-family-office-monitor-room',
    at: [9.75, -2],
    target: [9.75, -10],
    pitch: -0.02,
    chapter: 380,
    volume: 36,
    label: 'The separate Cha-R CCTV room facing its dark monitor bank',
    labelFr: 'La salle de vidéosurveillance Cha-R séparée face à son mur d’écrans sombre',
  }),
  mangaView({
    id: 'cha-r-office-aerial-plan',
    spaceId: 'tier-5-cha-r-family-office-hall',
    at: [-1.5, 0],
    target: [-1.5, -1],
    pitch: -1.5,
    eyeHeight: 32,
    chapter: 380,
    volume: 36,
    label: 'Aerial plan of the three published Cha-R office rooms',
    labelFr: 'Plan aérien des trois pièces publiées du bureau Cha-R',
    visibleSpaceIds: [
      'tier-5-cha-r-family-office-main-office',
      'tier-5-cha-r-family-office-bedroom',
      'tier-5-cha-r-family-office-monitor-room',
    ],
  }),
  mangaView({
    id: 'cha-r-warehouse-aerial-plan',
    spaceId: 'tier-5-warehouse',
    at: [21, -21],
    target: [21, -22],
    pitch: -1.5,
    eyeHeight: 90,
    chapter: 378,
    volume: 36,
    label: 'Aerial plan of the Cha-R warehouse and its crate rows',
    labelFr: 'Plan aérien de l’entrepôt Cha-R et de ses rangées de caisses',
    visibleSpaceIds: ['tier-5-warehouse'],
  }),
]
