export type PostcardStampCategory = 'official' | 'royal' | 'underworld' | 'expedition'
export type PostcardStampShape = 'round' | 'oval' | 'square' | 'ticket' | 'diamond'
export type PostcardStampTone =
  'formal' | 'military' | 'clinical' | 'ominous' | 'luxe' | 'playful' | 'gentle' | 'clandestine'

export interface PostcardStampDefinition {
  id: string
  category: PostcardStampCategory
  mark: string
  ink: string
  shape: PostcardStampShape
  tone: PostcardStampTone
  rotation: number
}

/** Opaque paper behind every seal, so the captured scene can never swallow its ink. */
export const POSTCARD_STAMP_BACKING = '#fffdf0'

/**
 * Every seal belongs to an authority or group aboard the Black Whale.  The
 * postcard deliberately keeps these as ink and type rather than importing
 * logos the manga never drew: they are souvenirs, not counterfeit canon.
 */
export const POSTCARD_STAMPS = [
  {
    id: 'kakin',
    category: 'official',
    mark: '♛',
    ink: '#a71930',
    shape: 'round',
    tone: 'luxe',
    rotation: 13,
  },
  {
    id: 'hunter',
    category: 'official',
    mark: '✦',
    ink: '#245b91',
    shape: 'square',
    tone: 'formal',
    rotation: -9,
  },
  {
    id: 'blackWhale',
    category: 'official',
    mark: '◖◗',
    ink: '#173f5f',
    shape: 'oval',
    tone: 'formal',
    rotation: 7,
  },
  {
    id: 'royalArmy',
    category: 'official',
    mark: '⚔',
    ink: '#8f172b',
    shape: 'square',
    tone: 'military',
    rotation: 0,
  },
  {
    id: 'justice',
    category: 'official',
    mark: '⚖',
    ink: '#22252a',
    shape: 'round',
    tone: 'formal',
    rotation: -3,
  },
  {
    id: 'police',
    category: 'official',
    mark: '◆',
    ink: '#1e4d78',
    shape: 'ticket',
    tone: 'military',
    rotation: 2,
  },
  {
    id: 'tribunal',
    category: 'official',
    mark: '§',
    ink: '#3c3c3c',
    shape: 'square',
    tone: 'formal',
    rotation: 0,
  },
  {
    id: 'hospital',
    category: 'official',
    mark: '✚',
    ink: '#187f79',
    shape: 'round',
    tone: 'clinical',
    rotation: -5,
  },
  {
    id: 'passengerControl',
    category: 'official',
    mark: '№',
    ink: '#486174',
    shape: 'ticket',
    tone: 'formal',
    rotation: 4,
  },
  {
    id: 'succession',
    category: 'official',
    mark: '♜',
    ink: '#532061',
    shape: 'round',
    tone: 'ominous',
    rotation: -7,
  },
  {
    id: 'seedUrn',
    category: 'official',
    mark: '♨',
    ink: '#6d286d',
    shape: 'oval',
    tone: 'ominous',
    rotation: 5,
  },
  {
    id: 'darkContinent',
    category: 'official',
    mark: '⌖',
    ink: '#236044',
    shape: 'diamond',
    tone: 'formal',
    rotation: 3,
  },
  {
    id: 'beyond',
    category: 'official',
    mark: '☄',
    ink: '#27633d',
    shape: 'round',
    tone: 'luxe',
    rotation: 11,
  },
  {
    id: 'permits',
    category: 'official',
    mark: '◎',
    ink: '#405d78',
    shape: 'ticket',
    tone: 'formal',
    rotation: -2,
  },
  {
    id: 'v6',
    category: 'official',
    mark: '✶',
    ink: '#564785',
    shape: 'diamond',
    tone: 'luxe',
    rotation: 0,
  },

  {
    id: 'benjamin',
    category: 'royal',
    mark: '♞',
    ink: '#8d1024',
    shape: 'square',
    tone: 'military',
    rotation: 0,
  },
  {
    id: 'camilla',
    category: 'royal',
    mark: '♕',
    ink: '#9d256f',
    shape: 'oval',
    tone: 'luxe',
    rotation: 8,
  },
  {
    id: 'zhangLei',
    category: 'royal',
    mark: '◉',
    ink: '#8a5c19',
    shape: 'round',
    tone: 'luxe',
    rotation: -4,
  },
  {
    id: 'tserriednich',
    category: 'royal',
    mark: '◬',
    ink: '#161616',
    shape: 'square',
    tone: 'ominous',
    rotation: 0,
  },
  {
    id: 'tubeppa',
    category: 'royal',
    mark: '⚗',
    ink: '#087f8c',
    shape: 'diamond',
    tone: 'clinical',
    rotation: -3,
  },
  {
    id: 'tyson',
    category: 'royal',
    mark: '♥',
    ink: '#d12d7d',
    shape: 'round',
    tone: 'playful',
    rotation: 9,
  },
  {
    id: 'luzurus',
    category: 'royal',
    mark: '☁',
    ink: '#657530',
    shape: 'oval',
    tone: 'playful',
    rotation: -8,
  },
  {
    id: 'saleSale',
    category: 'royal',
    mark: '✺',
    ink: '#a9491a',
    shape: 'round',
    tone: 'playful',
    rotation: 12,
  },
  {
    id: 'halkenburg',
    category: 'royal',
    mark: '➶',
    ink: '#284c78',
    shape: 'ticket',
    tone: 'military',
    rotation: -1,
  },
  {
    id: 'kacho',
    category: 'royal',
    mark: '♫',
    ink: '#9d4452',
    shape: 'oval',
    tone: 'gentle',
    rotation: 6,
  },
  {
    id: 'fugetsu',
    category: 'royal',
    mark: '➳',
    ink: '#456b8a',
    shape: 'oval',
    tone: 'gentle',
    rotation: -6,
  },
  {
    id: 'momoze',
    category: 'royal',
    mark: '❀',
    ink: '#715686',
    shape: 'round',
    tone: 'gentle',
    rotation: 4,
  },
  {
    id: 'marayam',
    category: 'royal',
    mark: '♢',
    ink: '#278060',
    shape: 'round',
    tone: 'playful',
    rotation: -9,
  },
  {
    id: 'woble',
    category: 'royal',
    mark: '♔',
    ink: '#926212',
    shape: 'round',
    tone: 'playful',
    rotation: 7,
  },

  {
    id: 'xiYu',
    category: 'underworld',
    mark: '扇',
    ink: '#176c55',
    shape: 'diamond',
    tone: 'clandestine',
    rotation: -5,
  },
  {
    id: 'chaR',
    category: 'underworld',
    mark: '♣',
    ink: '#72283b',
    shape: 'square',
    tone: 'clandestine',
    rotation: 3,
  },
  {
    id: 'heilLy',
    category: 'underworld',
    mark: '✣',
    ink: '#46680a',
    shape: 'round',
    tone: 'ominous',
    rotation: -11,
  },
  {
    id: 'phantomTroupe',
    category: 'underworld',
    mark: '蛛',
    ink: '#151515',
    shape: 'round',
    tone: 'clandestine',
    rotation: 10,
  },
  {
    id: 'zoldyck',
    category: 'underworld',
    mark: '▥',
    ink: '#4a4d58',
    shape: 'diamond',
    tone: 'ominous',
    rotation: -2,
  },
  {
    id: 'hisoka',
    category: 'underworld',
    mark: '★♦',
    ink: '#a92787',
    shape: 'oval',
    tone: 'playful',
    rotation: 14,
  },

  {
    id: 'zodiacs',
    category: 'expedition',
    mark: '✧',
    ink: '#344c74',
    shape: 'round',
    tone: 'formal',
    rotation: -4,
  },
  {
    id: 'science',
    category: 'expedition',
    mark: '⌬',
    ink: '#147b82',
    shape: 'diamond',
    tone: 'clinical',
    rotation: 2,
  },
  {
    id: 'medical',
    category: 'expedition',
    mark: '⚕',
    ink: '#25826f',
    shape: 'round',
    tone: 'clinical',
    rotation: -3,
  },
  {
    id: 'defense',
    category: 'expedition',
    mark: '⬟',
    ink: '#3e5573',
    shape: 'square',
    tone: 'military',
    rotation: 1,
  },
  {
    id: 'intelligence',
    category: 'expedition',
    mark: '◈',
    ink: '#42445f',
    shape: 'ticket',
    tone: 'clandestine',
    rotation: -6,
  },
  {
    id: 'beyondCustody',
    category: 'expedition',
    mark: '▤',
    ink: '#693d31',
    shape: 'square',
    tone: 'military',
    rotation: 5,
  },
] as const satisfies readonly PostcardStampDefinition[]

export type PostcardStampId = (typeof POSTCARD_STAMPS)[number]['id']

export function postcardStamp(id: PostcardStampId): (typeof POSTCARD_STAMPS)[number] {
  return POSTCARD_STAMPS.find((stamp) => stamp.id === id) ?? POSTCARD_STAMPS[0]
}
